// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/iproto/comment/ControlPanelBean.proto

package google.iproto.comment;

public final class ControlPanelBeanProto {
  private ControlPanelBeanProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ControlPanelBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.iproto.ControlPanelBean)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *面板Id
     * </pre>
     *
     * <code>int32 panelid = 1;</code>
     */
    int getPanelid();

    /**
     * <pre>
     *面板名称
     * </pre>
     *
     * <code>string panelname = 2;</code>
     */
    java.lang.String getPanelname();
    /**
     * <pre>
     *面板名称
     * </pre>
     *
     * <code>string panelname = 2;</code>
     */
    com.google.protobuf.ByteString
        getPanelnameBytes();

    /**
     * <pre>
     *按键数据
     * </pre>
     *
     * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
     */
    java.util.List<google.iproto.comment.PanelChildBeanProto.PanelChildBean> 
        getChildbeanList();
    /**
     * <pre>
     *按键数据
     * </pre>
     *
     * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
     */
    google.iproto.comment.PanelChildBeanProto.PanelChildBean getChildbean(int index);
    /**
     * <pre>
     *按键数据
     * </pre>
     *
     * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
     */
    int getChildbeanCount();
    /**
     * <pre>
     *按键数据
     * </pre>
     *
     * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
     */
    java.util.List<? extends google.iproto.comment.PanelChildBeanProto.PanelChildBeanOrBuilder> 
        getChildbeanOrBuilderList();
    /**
     * <pre>
     *按键数据
     * </pre>
     *
     * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
     */
    google.iproto.comment.PanelChildBeanProto.PanelChildBeanOrBuilder getChildbeanOrBuilder(
        int index);
  }
  /**
   * <pre>
   *控制面板数据响应
   * </pre>
   *
   * Protobuf type {@code google.iproto.ControlPanelBean}
   */
  public  static final class ControlPanelBean extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.iproto.ControlPanelBean)
      ControlPanelBeanOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ControlPanelBean.newBuilder() to construct.
    private ControlPanelBean(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ControlPanelBean() {
      panelid_ = 0;
      panelname_ = "";
      childbean_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ControlPanelBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              panelid_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              panelname_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                childbean_ = new java.util.ArrayList<google.iproto.comment.PanelChildBeanProto.PanelChildBean>();
                mutable_bitField0_ |= 0x00000004;
              }
              childbean_.add(
                  input.readMessage(google.iproto.comment.PanelChildBeanProto.PanelChildBean.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          childbean_ = java.util.Collections.unmodifiableList(childbean_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.iproto.comment.ControlPanelBeanProto.internal_static_google_iproto_ControlPanelBean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.iproto.comment.ControlPanelBeanProto.internal_static_google_iproto_ControlPanelBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.iproto.comment.ControlPanelBeanProto.ControlPanelBean.class, google.iproto.comment.ControlPanelBeanProto.ControlPanelBean.Builder.class);
    }

    private int bitField0_;
    public static final int PANELID_FIELD_NUMBER = 1;
    private int panelid_;
    /**
     * <pre>
     *面板Id
     * </pre>
     *
     * <code>int32 panelid = 1;</code>
     */
    public int getPanelid() {
      return panelid_;
    }

    public static final int PANELNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object panelname_;
    /**
     * <pre>
     *面板名称
     * </pre>
     *
     * <code>string panelname = 2;</code>
     */
    public java.lang.String getPanelname() {
      java.lang.Object ref = panelname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        panelname_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *面板名称
     * </pre>
     *
     * <code>string panelname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPanelnameBytes() {
      java.lang.Object ref = panelname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        panelname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHILDBEAN_FIELD_NUMBER = 3;
    private java.util.List<google.iproto.comment.PanelChildBeanProto.PanelChildBean> childbean_;
    /**
     * <pre>
     *按键数据
     * </pre>
     *
     * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
     */
    public java.util.List<google.iproto.comment.PanelChildBeanProto.PanelChildBean> getChildbeanList() {
      return childbean_;
    }
    /**
     * <pre>
     *按键数据
     * </pre>
     *
     * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
     */
    public java.util.List<? extends google.iproto.comment.PanelChildBeanProto.PanelChildBeanOrBuilder> 
        getChildbeanOrBuilderList() {
      return childbean_;
    }
    /**
     * <pre>
     *按键数据
     * </pre>
     *
     * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
     */
    public int getChildbeanCount() {
      return childbean_.size();
    }
    /**
     * <pre>
     *按键数据
     * </pre>
     *
     * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
     */
    public google.iproto.comment.PanelChildBeanProto.PanelChildBean getChildbean(int index) {
      return childbean_.get(index);
    }
    /**
     * <pre>
     *按键数据
     * </pre>
     *
     * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
     */
    public google.iproto.comment.PanelChildBeanProto.PanelChildBeanOrBuilder getChildbeanOrBuilder(
        int index) {
      return childbean_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (panelid_ != 0) {
        output.writeInt32(1, panelid_);
      }
      if (!getPanelnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, panelname_);
      }
      for (int i = 0; i < childbean_.size(); i++) {
        output.writeMessage(3, childbean_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (panelid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, panelid_);
      }
      if (!getPanelnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, panelname_);
      }
      for (int i = 0; i < childbean_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, childbean_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof google.iproto.comment.ControlPanelBeanProto.ControlPanelBean)) {
        return super.equals(obj);
      }
      google.iproto.comment.ControlPanelBeanProto.ControlPanelBean other = (google.iproto.comment.ControlPanelBeanProto.ControlPanelBean) obj;

      boolean result = true;
      result = result && (getPanelid()
          == other.getPanelid());
      result = result && getPanelname()
          .equals(other.getPanelname());
      result = result && getChildbeanList()
          .equals(other.getChildbeanList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PANELID_FIELD_NUMBER;
      hash = (53 * hash) + getPanelid();
      hash = (37 * hash) + PANELNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPanelname().hashCode();
      if (getChildbeanCount() > 0) {
        hash = (37 * hash) + CHILDBEAN_FIELD_NUMBER;
        hash = (53 * hash) + getChildbeanList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static google.iproto.comment.ControlPanelBeanProto.ControlPanelBean parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.comment.ControlPanelBeanProto.ControlPanelBean parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.comment.ControlPanelBeanProto.ControlPanelBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.comment.ControlPanelBeanProto.ControlPanelBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.comment.ControlPanelBeanProto.ControlPanelBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.comment.ControlPanelBeanProto.ControlPanelBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.comment.ControlPanelBeanProto.ControlPanelBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.iproto.comment.ControlPanelBeanProto.ControlPanelBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.iproto.comment.ControlPanelBeanProto.ControlPanelBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static google.iproto.comment.ControlPanelBeanProto.ControlPanelBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.iproto.comment.ControlPanelBeanProto.ControlPanelBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.iproto.comment.ControlPanelBeanProto.ControlPanelBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(google.iproto.comment.ControlPanelBeanProto.ControlPanelBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *控制面板数据响应
     * </pre>
     *
     * Protobuf type {@code google.iproto.ControlPanelBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.iproto.ControlPanelBean)
        google.iproto.comment.ControlPanelBeanProto.ControlPanelBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.iproto.comment.ControlPanelBeanProto.internal_static_google_iproto_ControlPanelBean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.iproto.comment.ControlPanelBeanProto.internal_static_google_iproto_ControlPanelBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                google.iproto.comment.ControlPanelBeanProto.ControlPanelBean.class, google.iproto.comment.ControlPanelBeanProto.ControlPanelBean.Builder.class);
      }

      // Construct using google.iproto.comment.ControlPanelBeanProto.ControlPanelBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChildbeanFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        panelid_ = 0;

        panelname_ = "";

        if (childbeanBuilder_ == null) {
          childbean_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          childbeanBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.iproto.comment.ControlPanelBeanProto.internal_static_google_iproto_ControlPanelBean_descriptor;
      }

      public google.iproto.comment.ControlPanelBeanProto.ControlPanelBean getDefaultInstanceForType() {
        return google.iproto.comment.ControlPanelBeanProto.ControlPanelBean.getDefaultInstance();
      }

      public google.iproto.comment.ControlPanelBeanProto.ControlPanelBean build() {
        google.iproto.comment.ControlPanelBeanProto.ControlPanelBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public google.iproto.comment.ControlPanelBeanProto.ControlPanelBean buildPartial() {
        google.iproto.comment.ControlPanelBeanProto.ControlPanelBean result = new google.iproto.comment.ControlPanelBeanProto.ControlPanelBean(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.panelid_ = panelid_;
        result.panelname_ = panelname_;
        if (childbeanBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            childbean_ = java.util.Collections.unmodifiableList(childbean_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.childbean_ = childbean_;
        } else {
          result.childbean_ = childbeanBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.iproto.comment.ControlPanelBeanProto.ControlPanelBean) {
          return mergeFrom((google.iproto.comment.ControlPanelBeanProto.ControlPanelBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(google.iproto.comment.ControlPanelBeanProto.ControlPanelBean other) {
        if (other == google.iproto.comment.ControlPanelBeanProto.ControlPanelBean.getDefaultInstance()) return this;
        if (other.getPanelid() != 0) {
          setPanelid(other.getPanelid());
        }
        if (!other.getPanelname().isEmpty()) {
          panelname_ = other.panelname_;
          onChanged();
        }
        if (childbeanBuilder_ == null) {
          if (!other.childbean_.isEmpty()) {
            if (childbean_.isEmpty()) {
              childbean_ = other.childbean_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureChildbeanIsMutable();
              childbean_.addAll(other.childbean_);
            }
            onChanged();
          }
        } else {
          if (!other.childbean_.isEmpty()) {
            if (childbeanBuilder_.isEmpty()) {
              childbeanBuilder_.dispose();
              childbeanBuilder_ = null;
              childbean_ = other.childbean_;
              bitField0_ = (bitField0_ & ~0x00000004);
              childbeanBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getChildbeanFieldBuilder() : null;
            } else {
              childbeanBuilder_.addAllMessages(other.childbean_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        google.iproto.comment.ControlPanelBeanProto.ControlPanelBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (google.iproto.comment.ControlPanelBeanProto.ControlPanelBean) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int panelid_ ;
      /**
       * <pre>
       *面板Id
       * </pre>
       *
       * <code>int32 panelid = 1;</code>
       */
      public int getPanelid() {
        return panelid_;
      }
      /**
       * <pre>
       *面板Id
       * </pre>
       *
       * <code>int32 panelid = 1;</code>
       */
      public Builder setPanelid(int value) {
        
        panelid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *面板Id
       * </pre>
       *
       * <code>int32 panelid = 1;</code>
       */
      public Builder clearPanelid() {
        
        panelid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object panelname_ = "";
      /**
       * <pre>
       *面板名称
       * </pre>
       *
       * <code>string panelname = 2;</code>
       */
      public java.lang.String getPanelname() {
        java.lang.Object ref = panelname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          panelname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *面板名称
       * </pre>
       *
       * <code>string panelname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPanelnameBytes() {
        java.lang.Object ref = panelname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          panelname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *面板名称
       * </pre>
       *
       * <code>string panelname = 2;</code>
       */
      public Builder setPanelname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        panelname_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *面板名称
       * </pre>
       *
       * <code>string panelname = 2;</code>
       */
      public Builder clearPanelname() {
        
        panelname_ = getDefaultInstance().getPanelname();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *面板名称
       * </pre>
       *
       * <code>string panelname = 2;</code>
       */
      public Builder setPanelnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        panelname_ = value;
        onChanged();
        return this;
      }

      private java.util.List<google.iproto.comment.PanelChildBeanProto.PanelChildBean> childbean_ =
        java.util.Collections.emptyList();
      private void ensureChildbeanIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          childbean_ = new java.util.ArrayList<google.iproto.comment.PanelChildBeanProto.PanelChildBean>(childbean_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          google.iproto.comment.PanelChildBeanProto.PanelChildBean, google.iproto.comment.PanelChildBeanProto.PanelChildBean.Builder, google.iproto.comment.PanelChildBeanProto.PanelChildBeanOrBuilder> childbeanBuilder_;

      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public java.util.List<google.iproto.comment.PanelChildBeanProto.PanelChildBean> getChildbeanList() {
        if (childbeanBuilder_ == null) {
          return java.util.Collections.unmodifiableList(childbean_);
        } else {
          return childbeanBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public int getChildbeanCount() {
        if (childbeanBuilder_ == null) {
          return childbean_.size();
        } else {
          return childbeanBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public google.iproto.comment.PanelChildBeanProto.PanelChildBean getChildbean(int index) {
        if (childbeanBuilder_ == null) {
          return childbean_.get(index);
        } else {
          return childbeanBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public Builder setChildbean(
          int index, google.iproto.comment.PanelChildBeanProto.PanelChildBean value) {
        if (childbeanBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildbeanIsMutable();
          childbean_.set(index, value);
          onChanged();
        } else {
          childbeanBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public Builder setChildbean(
          int index, google.iproto.comment.PanelChildBeanProto.PanelChildBean.Builder builderForValue) {
        if (childbeanBuilder_ == null) {
          ensureChildbeanIsMutable();
          childbean_.set(index, builderForValue.build());
          onChanged();
        } else {
          childbeanBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public Builder addChildbean(google.iproto.comment.PanelChildBeanProto.PanelChildBean value) {
        if (childbeanBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildbeanIsMutable();
          childbean_.add(value);
          onChanged();
        } else {
          childbeanBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public Builder addChildbean(
          int index, google.iproto.comment.PanelChildBeanProto.PanelChildBean value) {
        if (childbeanBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildbeanIsMutable();
          childbean_.add(index, value);
          onChanged();
        } else {
          childbeanBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public Builder addChildbean(
          google.iproto.comment.PanelChildBeanProto.PanelChildBean.Builder builderForValue) {
        if (childbeanBuilder_ == null) {
          ensureChildbeanIsMutable();
          childbean_.add(builderForValue.build());
          onChanged();
        } else {
          childbeanBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public Builder addChildbean(
          int index, google.iproto.comment.PanelChildBeanProto.PanelChildBean.Builder builderForValue) {
        if (childbeanBuilder_ == null) {
          ensureChildbeanIsMutable();
          childbean_.add(index, builderForValue.build());
          onChanged();
        } else {
          childbeanBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public Builder addAllChildbean(
          java.lang.Iterable<? extends google.iproto.comment.PanelChildBeanProto.PanelChildBean> values) {
        if (childbeanBuilder_ == null) {
          ensureChildbeanIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, childbean_);
          onChanged();
        } else {
          childbeanBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public Builder clearChildbean() {
        if (childbeanBuilder_ == null) {
          childbean_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          childbeanBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public Builder removeChildbean(int index) {
        if (childbeanBuilder_ == null) {
          ensureChildbeanIsMutable();
          childbean_.remove(index);
          onChanged();
        } else {
          childbeanBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public google.iproto.comment.PanelChildBeanProto.PanelChildBean.Builder getChildbeanBuilder(
          int index) {
        return getChildbeanFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public google.iproto.comment.PanelChildBeanProto.PanelChildBeanOrBuilder getChildbeanOrBuilder(
          int index) {
        if (childbeanBuilder_ == null) {
          return childbean_.get(index);  } else {
          return childbeanBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public java.util.List<? extends google.iproto.comment.PanelChildBeanProto.PanelChildBeanOrBuilder> 
           getChildbeanOrBuilderList() {
        if (childbeanBuilder_ != null) {
          return childbeanBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(childbean_);
        }
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public google.iproto.comment.PanelChildBeanProto.PanelChildBean.Builder addChildbeanBuilder() {
        return getChildbeanFieldBuilder().addBuilder(
            google.iproto.comment.PanelChildBeanProto.PanelChildBean.getDefaultInstance());
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public google.iproto.comment.PanelChildBeanProto.PanelChildBean.Builder addChildbeanBuilder(
          int index) {
        return getChildbeanFieldBuilder().addBuilder(
            index, google.iproto.comment.PanelChildBeanProto.PanelChildBean.getDefaultInstance());
      }
      /**
       * <pre>
       *按键数据
       * </pre>
       *
       * <code>repeated .google.iproto.PanelChildBean childbean = 3;</code>
       */
      public java.util.List<google.iproto.comment.PanelChildBeanProto.PanelChildBean.Builder> 
           getChildbeanBuilderList() {
        return getChildbeanFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          google.iproto.comment.PanelChildBeanProto.PanelChildBean, google.iproto.comment.PanelChildBeanProto.PanelChildBean.Builder, google.iproto.comment.PanelChildBeanProto.PanelChildBeanOrBuilder> 
          getChildbeanFieldBuilder() {
        if (childbeanBuilder_ == null) {
          childbeanBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              google.iproto.comment.PanelChildBeanProto.PanelChildBean, google.iproto.comment.PanelChildBeanProto.PanelChildBean.Builder, google.iproto.comment.PanelChildBeanProto.PanelChildBeanOrBuilder>(
                  childbean_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          childbean_ = null;
        }
        return childbeanBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:google.iproto.ControlPanelBean)
    }

    // @@protoc_insertion_point(class_scope:google.iproto.ControlPanelBean)
    private static final google.iproto.comment.ControlPanelBeanProto.ControlPanelBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new google.iproto.comment.ControlPanelBeanProto.ControlPanelBean();
    }

    public static google.iproto.comment.ControlPanelBeanProto.ControlPanelBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ControlPanelBean>
        PARSER = new com.google.protobuf.AbstractParser<ControlPanelBean>() {
      public ControlPanelBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ControlPanelBean(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ControlPanelBean> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ControlPanelBean> getParserForType() {
      return PARSER;
    }

    public google.iproto.comment.ControlPanelBeanProto.ControlPanelBean getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_iproto_ControlPanelBean_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_iproto_ControlPanelBean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,google/iproto/comment/ControlPanelBean" +
      ".proto\022\rgoogle.iproto\032*google/iproto/com" +
      "ment/PanelChildBean.proto\"h\n\020ControlPane" +
      "lBean\022\017\n\007panelid\030\001 \001(\005\022\021\n\tpanelname\030\002 \001(" +
      "\t\0220\n\tchildbean\030\003 \003(\0132\035.google.iproto.Pan" +
      "elChildBeanB.\n\025google.iproto.commentB\025Co" +
      "ntrolPanelBeanProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          google.iproto.comment.PanelChildBeanProto.getDescriptor(),
        }, assigner);
    internal_static_google_iproto_ControlPanelBean_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_iproto_ControlPanelBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_iproto_ControlPanelBean_descriptor,
        new java.lang.String[] { "Panelid", "Panelname", "Childbean", });
    google.iproto.comment.PanelChildBeanProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
