// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/iproto/mqtt/p0303_Scene_bindscene2sensor.proto

package google.iproto.mqtt;

public final class SceneBindScene2SensorProto {
  private SceneBindScene2SensorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface scene_bindscene2sensorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.iproto.scene_bindscene2sensor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *传感器的ID信息
     * </pre>
     *
     * <code>int32 dev_sensor_id = 1;</code>
     */
    int getDevSensorId();

    /**
     * <pre>
     *需要绑定的场景ID信息
     * </pre>
     *
     * <code>repeated int32 scene_id = 2;</code>
     */
    java.util.List<java.lang.Integer> getSceneIdList();
    /**
     * <pre>
     *需要绑定的场景ID信息
     * </pre>
     *
     * <code>repeated int32 scene_id = 2;</code>
     */
    int getSceneIdCount();
    /**
     * <pre>
     *需要绑定的场景ID信息
     * </pre>
     *
     * <code>repeated int32 scene_id = 2;</code>
     */
    int getSceneId(int index);

    /**
     * <pre>
     *操作类型：1: 绑定， 0：解除绑定
     * </pre>
     *
     * <code>int32 optcmd = 3;</code>
     */
    int getOptcmd();
  }
  /**
   * <pre>
   * 将场景绑定到传感器 
   * </pre>
   *
   * Protobuf type {@code google.iproto.scene_bindscene2sensor}
   */
  public  static final class scene_bindscene2sensor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.iproto.scene_bindscene2sensor)
      scene_bindscene2sensorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use scene_bindscene2sensor.newBuilder() to construct.
    private scene_bindscene2sensor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private scene_bindscene2sensor() {
      devSensorId_ = 0;
      sceneId_ = java.util.Collections.emptyList();
      optcmd_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private scene_bindscene2sensor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              devSensorId_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                sceneId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              sceneId_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                sceneId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                sceneId_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {

              optcmd_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          sceneId_ = java.util.Collections.unmodifiableList(sceneId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.iproto.mqtt.SceneBindScene2SensorProto.internal_static_google_iproto_scene_bindscene2sensor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.iproto.mqtt.SceneBindScene2SensorProto.internal_static_google_iproto_scene_bindscene2sensor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor.class, google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor.Builder.class);
    }

    private int bitField0_;
    public static final int DEV_SENSOR_ID_FIELD_NUMBER = 1;
    private int devSensorId_;
    /**
     * <pre>
     *传感器的ID信息
     * </pre>
     *
     * <code>int32 dev_sensor_id = 1;</code>
     */
    public int getDevSensorId() {
      return devSensorId_;
    }

    public static final int SCENE_ID_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> sceneId_;
    /**
     * <pre>
     *需要绑定的场景ID信息
     * </pre>
     *
     * <code>repeated int32 scene_id = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getSceneIdList() {
      return sceneId_;
    }
    /**
     * <pre>
     *需要绑定的场景ID信息
     * </pre>
     *
     * <code>repeated int32 scene_id = 2;</code>
     */
    public int getSceneIdCount() {
      return sceneId_.size();
    }
    /**
     * <pre>
     *需要绑定的场景ID信息
     * </pre>
     *
     * <code>repeated int32 scene_id = 2;</code>
     */
    public int getSceneId(int index) {
      return sceneId_.get(index);
    }
    private int sceneIdMemoizedSerializedSize = -1;

    public static final int OPTCMD_FIELD_NUMBER = 3;
    private int optcmd_;
    /**
     * <pre>
     *操作类型：1: 绑定， 0：解除绑定
     * </pre>
     *
     * <code>int32 optcmd = 3;</code>
     */
    public int getOptcmd() {
      return optcmd_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (devSensorId_ != 0) {
        output.writeInt32(1, devSensorId_);
      }
      if (getSceneIdList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(sceneIdMemoizedSerializedSize);
      }
      for (int i = 0; i < sceneId_.size(); i++) {
        output.writeInt32NoTag(sceneId_.get(i));
      }
      if (optcmd_ != 0) {
        output.writeInt32(3, optcmd_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (devSensorId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, devSensorId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sceneId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(sceneId_.get(i));
        }
        size += dataSize;
        if (!getSceneIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        sceneIdMemoizedSerializedSize = dataSize;
      }
      if (optcmd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, optcmd_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor)) {
        return super.equals(obj);
      }
      google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor other = (google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor) obj;

      boolean result = true;
      result = result && (getDevSensorId()
          == other.getDevSensorId());
      result = result && getSceneIdList()
          .equals(other.getSceneIdList());
      result = result && (getOptcmd()
          == other.getOptcmd());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEV_SENSOR_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDevSensorId();
      if (getSceneIdCount() > 0) {
        hash = (37 * hash) + SCENE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getSceneIdList().hashCode();
      }
      hash = (37 * hash) + OPTCMD_FIELD_NUMBER;
      hash = (53 * hash) + getOptcmd();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 将场景绑定到传感器 
     * </pre>
     *
     * Protobuf type {@code google.iproto.scene_bindscene2sensor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.iproto.scene_bindscene2sensor)
        google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.iproto.mqtt.SceneBindScene2SensorProto.internal_static_google_iproto_scene_bindscene2sensor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.iproto.mqtt.SceneBindScene2SensorProto.internal_static_google_iproto_scene_bindscene2sensor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor.class, google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor.Builder.class);
      }

      // Construct using google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        devSensorId_ = 0;

        sceneId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        optcmd_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.iproto.mqtt.SceneBindScene2SensorProto.internal_static_google_iproto_scene_bindscene2sensor_descriptor;
      }

      public google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor getDefaultInstanceForType() {
        return google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor.getDefaultInstance();
      }

      public google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor build() {
        google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor buildPartial() {
        google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor result = new google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.devSensorId_ = devSensorId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          sceneId_ = java.util.Collections.unmodifiableList(sceneId_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.sceneId_ = sceneId_;
        result.optcmd_ = optcmd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor) {
          return mergeFrom((google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor other) {
        if (other == google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor.getDefaultInstance()) return this;
        if (other.getDevSensorId() != 0) {
          setDevSensorId(other.getDevSensorId());
        }
        if (!other.sceneId_.isEmpty()) {
          if (sceneId_.isEmpty()) {
            sceneId_ = other.sceneId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSceneIdIsMutable();
            sceneId_.addAll(other.sceneId_);
          }
          onChanged();
        }
        if (other.getOptcmd() != 0) {
          setOptcmd(other.getOptcmd());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int devSensorId_ ;
      /**
       * <pre>
       *传感器的ID信息
       * </pre>
       *
       * <code>int32 dev_sensor_id = 1;</code>
       */
      public int getDevSensorId() {
        return devSensorId_;
      }
      /**
       * <pre>
       *传感器的ID信息
       * </pre>
       *
       * <code>int32 dev_sensor_id = 1;</code>
       */
      public Builder setDevSensorId(int value) {
        
        devSensorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *传感器的ID信息
       * </pre>
       *
       * <code>int32 dev_sensor_id = 1;</code>
       */
      public Builder clearDevSensorId() {
        
        devSensorId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> sceneId_ = java.util.Collections.emptyList();
      private void ensureSceneIdIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          sceneId_ = new java.util.ArrayList<java.lang.Integer>(sceneId_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       *需要绑定的场景ID信息
       * </pre>
       *
       * <code>repeated int32 scene_id = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getSceneIdList() {
        return java.util.Collections.unmodifiableList(sceneId_);
      }
      /**
       * <pre>
       *需要绑定的场景ID信息
       * </pre>
       *
       * <code>repeated int32 scene_id = 2;</code>
       */
      public int getSceneIdCount() {
        return sceneId_.size();
      }
      /**
       * <pre>
       *需要绑定的场景ID信息
       * </pre>
       *
       * <code>repeated int32 scene_id = 2;</code>
       */
      public int getSceneId(int index) {
        return sceneId_.get(index);
      }
      /**
       * <pre>
       *需要绑定的场景ID信息
       * </pre>
       *
       * <code>repeated int32 scene_id = 2;</code>
       */
      public Builder setSceneId(
          int index, int value) {
        ensureSceneIdIsMutable();
        sceneId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *需要绑定的场景ID信息
       * </pre>
       *
       * <code>repeated int32 scene_id = 2;</code>
       */
      public Builder addSceneId(int value) {
        ensureSceneIdIsMutable();
        sceneId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *需要绑定的场景ID信息
       * </pre>
       *
       * <code>repeated int32 scene_id = 2;</code>
       */
      public Builder addAllSceneId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSceneIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sceneId_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *需要绑定的场景ID信息
       * </pre>
       *
       * <code>repeated int32 scene_id = 2;</code>
       */
      public Builder clearSceneId() {
        sceneId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private int optcmd_ ;
      /**
       * <pre>
       *操作类型：1: 绑定， 0：解除绑定
       * </pre>
       *
       * <code>int32 optcmd = 3;</code>
       */
      public int getOptcmd() {
        return optcmd_;
      }
      /**
       * <pre>
       *操作类型：1: 绑定， 0：解除绑定
       * </pre>
       *
       * <code>int32 optcmd = 3;</code>
       */
      public Builder setOptcmd(int value) {
        
        optcmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *操作类型：1: 绑定， 0：解除绑定
       * </pre>
       *
       * <code>int32 optcmd = 3;</code>
       */
      public Builder clearOptcmd() {
        
        optcmd_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:google.iproto.scene_bindscene2sensor)
    }

    // @@protoc_insertion_point(class_scope:google.iproto.scene_bindscene2sensor)
    private static final google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor();
    }

    public static google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<scene_bindscene2sensor>
        PARSER = new com.google.protobuf.AbstractParser<scene_bindscene2sensor>() {
      public scene_bindscene2sensor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new scene_bindscene2sensor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<scene_bindscene2sensor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<scene_bindscene2sensor> getParserForType() {
      return PARSER;
    }

    public google.iproto.mqtt.SceneBindScene2SensorProto.scene_bindscene2sensor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_iproto_scene_bindscene2sensor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_iproto_scene_bindscene2sensor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5google/iproto/mqtt/p0303_Scene_bindsce" +
      "ne2sensor.proto\022\rgoogle.iproto\"Q\n\026scene_" +
      "bindscene2sensor\022\025\n\rdev_sensor_id\030\001 \001(\005\022" +
      "\020\n\010scene_id\030\002 \003(\005\022\016\n\006optcmd\030\003 \001(\005B0\n\022goo" +
      "gle.iproto.mqttB\032SceneBindScene2SensorPr" +
      "otob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_google_iproto_scene_bindscene2sensor_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_iproto_scene_bindscene2sensor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_iproto_scene_bindscene2sensor_descriptor,
        new java.lang.String[] { "DevSensorId", "SceneId", "Optcmd", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
