// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/iproto/mqtt/p0705_SwSys_timeropt.proto

package google.iproto.mqtt;

public final class SwsystimeropterateProto {
  private SwsystimeropterateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface timer_operateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.iproto.timer_operate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *服务器提供的系统时间
     * </pre>
     *
     * <code>int64 systime = 1;</code>
     */
    long getSystime();

    /**
     * <pre>
     *列表ID
     * </pre>
     *
     * <code>int32 timingid = 2;</code>
     */
    int getTimingid();

    /**
     * <pre>
     *定时器列表，每次将该场景所有定时器下发给设备侧
     * </pre>
     *
     * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
     */
    java.util.List<google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl> 
        getTimerListList();
    /**
     * <pre>
     *定时器列表，每次将该场景所有定时器下发给设备侧
     * </pre>
     *
     * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
     */
    google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl getTimerList(int index);
    /**
     * <pre>
     *定时器列表，每次将该场景所有定时器下发给设备侧
     * </pre>
     *
     * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
     */
    int getTimerListCount();
    /**
     * <pre>
     *定时器列表，每次将该场景所有定时器下发给设备侧
     * </pre>
     *
     * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
     */
    java.util.List<? extends google.iproto.mqtt.SwsystimerctrlProto.timer_ctrlOrBuilder> 
        getTimerListOrBuilderList();
    /**
     * <pre>
     *定时器列表，每次将该场景所有定时器下发给设备侧
     * </pre>
     *
     * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
     */
    google.iproto.mqtt.SwsystimerctrlProto.timer_ctrlOrBuilder getTimerListOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 用户场景定时器定义
   * 说明：一个家庭为单位，最多允许创建64个场景定时器；
   *       一个场景里面，最多只通译创建14个场景定时器；
   *       服务器侧对定时器总条数做判断
   *       定时器下发时，以场景为单位下发
   * </pre>
   *
   * Protobuf type {@code google.iproto.timer_operate}
   */
  public  static final class timer_operate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.iproto.timer_operate)
      timer_operateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use timer_operate.newBuilder() to construct.
    private timer_operate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private timer_operate() {
      systime_ = 0L;
      timingid_ = 0;
      timerList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private timer_operate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              systime_ = input.readInt64();
              break;
            }
            case 16: {

              timingid_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                timerList_ = new java.util.ArrayList<google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl>();
                mutable_bitField0_ |= 0x00000004;
              }
              timerList_.add(
                  input.readMessage(google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          timerList_ = java.util.Collections.unmodifiableList(timerList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.iproto.mqtt.SwsystimeropterateProto.internal_static_google_iproto_timer_operate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.iproto.mqtt.SwsystimeropterateProto.internal_static_google_iproto_timer_operate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.iproto.mqtt.SwsystimeropterateProto.timer_operate.class, google.iproto.mqtt.SwsystimeropterateProto.timer_operate.Builder.class);
    }

    private int bitField0_;
    public static final int SYSTIME_FIELD_NUMBER = 1;
    private long systime_;
    /**
     * <pre>
     *服务器提供的系统时间
     * </pre>
     *
     * <code>int64 systime = 1;</code>
     */
    public long getSystime() {
      return systime_;
    }

    public static final int TIMINGID_FIELD_NUMBER = 2;
    private int timingid_;
    /**
     * <pre>
     *列表ID
     * </pre>
     *
     * <code>int32 timingid = 2;</code>
     */
    public int getTimingid() {
      return timingid_;
    }

    public static final int TIMER_LIST_FIELD_NUMBER = 3;
    private java.util.List<google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl> timerList_;
    /**
     * <pre>
     *定时器列表，每次将该场景所有定时器下发给设备侧
     * </pre>
     *
     * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
     */
    public java.util.List<google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl> getTimerListList() {
      return timerList_;
    }
    /**
     * <pre>
     *定时器列表，每次将该场景所有定时器下发给设备侧
     * </pre>
     *
     * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
     */
    public java.util.List<? extends google.iproto.mqtt.SwsystimerctrlProto.timer_ctrlOrBuilder> 
        getTimerListOrBuilderList() {
      return timerList_;
    }
    /**
     * <pre>
     *定时器列表，每次将该场景所有定时器下发给设备侧
     * </pre>
     *
     * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
     */
    public int getTimerListCount() {
      return timerList_.size();
    }
    /**
     * <pre>
     *定时器列表，每次将该场景所有定时器下发给设备侧
     * </pre>
     *
     * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
     */
    public google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl getTimerList(int index) {
      return timerList_.get(index);
    }
    /**
     * <pre>
     *定时器列表，每次将该场景所有定时器下发给设备侧
     * </pre>
     *
     * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
     */
    public google.iproto.mqtt.SwsystimerctrlProto.timer_ctrlOrBuilder getTimerListOrBuilder(
        int index) {
      return timerList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (systime_ != 0L) {
        output.writeInt64(1, systime_);
      }
      if (timingid_ != 0) {
        output.writeInt32(2, timingid_);
      }
      for (int i = 0; i < timerList_.size(); i++) {
        output.writeMessage(3, timerList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (systime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, systime_);
      }
      if (timingid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, timingid_);
      }
      for (int i = 0; i < timerList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, timerList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof google.iproto.mqtt.SwsystimeropterateProto.timer_operate)) {
        return super.equals(obj);
      }
      google.iproto.mqtt.SwsystimeropterateProto.timer_operate other = (google.iproto.mqtt.SwsystimeropterateProto.timer_operate) obj;

      boolean result = true;
      result = result && (getSystime()
          == other.getSystime());
      result = result && (getTimingid()
          == other.getTimingid());
      result = result && getTimerListList()
          .equals(other.getTimerListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SYSTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSystime());
      hash = (37 * hash) + TIMINGID_FIELD_NUMBER;
      hash = (53 * hash) + getTimingid();
      if (getTimerListCount() > 0) {
        hash = (37 * hash) + TIMER_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getTimerListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static google.iproto.mqtt.SwsystimeropterateProto.timer_operate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.mqtt.SwsystimeropterateProto.timer_operate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.mqtt.SwsystimeropterateProto.timer_operate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.mqtt.SwsystimeropterateProto.timer_operate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.mqtt.SwsystimeropterateProto.timer_operate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.mqtt.SwsystimeropterateProto.timer_operate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.mqtt.SwsystimeropterateProto.timer_operate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.iproto.mqtt.SwsystimeropterateProto.timer_operate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.iproto.mqtt.SwsystimeropterateProto.timer_operate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static google.iproto.mqtt.SwsystimeropterateProto.timer_operate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.iproto.mqtt.SwsystimeropterateProto.timer_operate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.iproto.mqtt.SwsystimeropterateProto.timer_operate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(google.iproto.mqtt.SwsystimeropterateProto.timer_operate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 用户场景定时器定义
     * 说明：一个家庭为单位，最多允许创建64个场景定时器；
     *       一个场景里面，最多只通译创建14个场景定时器；
     *       服务器侧对定时器总条数做判断
     *       定时器下发时，以场景为单位下发
     * </pre>
     *
     * Protobuf type {@code google.iproto.timer_operate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.iproto.timer_operate)
        google.iproto.mqtt.SwsystimeropterateProto.timer_operateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.iproto.mqtt.SwsystimeropterateProto.internal_static_google_iproto_timer_operate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.iproto.mqtt.SwsystimeropterateProto.internal_static_google_iproto_timer_operate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                google.iproto.mqtt.SwsystimeropterateProto.timer_operate.class, google.iproto.mqtt.SwsystimeropterateProto.timer_operate.Builder.class);
      }

      // Construct using google.iproto.mqtt.SwsystimeropterateProto.timer_operate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTimerListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        systime_ = 0L;

        timingid_ = 0;

        if (timerListBuilder_ == null) {
          timerList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          timerListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.iproto.mqtt.SwsystimeropterateProto.internal_static_google_iproto_timer_operate_descriptor;
      }

      public google.iproto.mqtt.SwsystimeropterateProto.timer_operate getDefaultInstanceForType() {
        return google.iproto.mqtt.SwsystimeropterateProto.timer_operate.getDefaultInstance();
      }

      public google.iproto.mqtt.SwsystimeropterateProto.timer_operate build() {
        google.iproto.mqtt.SwsystimeropterateProto.timer_operate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public google.iproto.mqtt.SwsystimeropterateProto.timer_operate buildPartial() {
        google.iproto.mqtt.SwsystimeropterateProto.timer_operate result = new google.iproto.mqtt.SwsystimeropterateProto.timer_operate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.systime_ = systime_;
        result.timingid_ = timingid_;
        if (timerListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            timerList_ = java.util.Collections.unmodifiableList(timerList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.timerList_ = timerList_;
        } else {
          result.timerList_ = timerListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.iproto.mqtt.SwsystimeropterateProto.timer_operate) {
          return mergeFrom((google.iproto.mqtt.SwsystimeropterateProto.timer_operate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(google.iproto.mqtt.SwsystimeropterateProto.timer_operate other) {
        if (other == google.iproto.mqtt.SwsystimeropterateProto.timer_operate.getDefaultInstance()) return this;
        if (other.getSystime() != 0L) {
          setSystime(other.getSystime());
        }
        if (other.getTimingid() != 0) {
          setTimingid(other.getTimingid());
        }
        if (timerListBuilder_ == null) {
          if (!other.timerList_.isEmpty()) {
            if (timerList_.isEmpty()) {
              timerList_ = other.timerList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureTimerListIsMutable();
              timerList_.addAll(other.timerList_);
            }
            onChanged();
          }
        } else {
          if (!other.timerList_.isEmpty()) {
            if (timerListBuilder_.isEmpty()) {
              timerListBuilder_.dispose();
              timerListBuilder_ = null;
              timerList_ = other.timerList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              timerListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTimerListFieldBuilder() : null;
            } else {
              timerListBuilder_.addAllMessages(other.timerList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        google.iproto.mqtt.SwsystimeropterateProto.timer_operate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (google.iproto.mqtt.SwsystimeropterateProto.timer_operate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long systime_ ;
      /**
       * <pre>
       *服务器提供的系统时间
       * </pre>
       *
       * <code>int64 systime = 1;</code>
       */
      public long getSystime() {
        return systime_;
      }
      /**
       * <pre>
       *服务器提供的系统时间
       * </pre>
       *
       * <code>int64 systime = 1;</code>
       */
      public Builder setSystime(long value) {
        
        systime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器提供的系统时间
       * </pre>
       *
       * <code>int64 systime = 1;</code>
       */
      public Builder clearSystime() {
        
        systime_ = 0L;
        onChanged();
        return this;
      }

      private int timingid_ ;
      /**
       * <pre>
       *列表ID
       * </pre>
       *
       * <code>int32 timingid = 2;</code>
       */
      public int getTimingid() {
        return timingid_;
      }
      /**
       * <pre>
       *列表ID
       * </pre>
       *
       * <code>int32 timingid = 2;</code>
       */
      public Builder setTimingid(int value) {
        
        timingid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *列表ID
       * </pre>
       *
       * <code>int32 timingid = 2;</code>
       */
      public Builder clearTimingid() {
        
        timingid_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl> timerList_ =
        java.util.Collections.emptyList();
      private void ensureTimerListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          timerList_ = new java.util.ArrayList<google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl>(timerList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl, google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl.Builder, google.iproto.mqtt.SwsystimerctrlProto.timer_ctrlOrBuilder> timerListBuilder_;

      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public java.util.List<google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl> getTimerListList() {
        if (timerListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(timerList_);
        } else {
          return timerListBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public int getTimerListCount() {
        if (timerListBuilder_ == null) {
          return timerList_.size();
        } else {
          return timerListBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl getTimerList(int index) {
        if (timerListBuilder_ == null) {
          return timerList_.get(index);
        } else {
          return timerListBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public Builder setTimerList(
          int index, google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl value) {
        if (timerListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimerListIsMutable();
          timerList_.set(index, value);
          onChanged();
        } else {
          timerListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public Builder setTimerList(
          int index, google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl.Builder builderForValue) {
        if (timerListBuilder_ == null) {
          ensureTimerListIsMutable();
          timerList_.set(index, builderForValue.build());
          onChanged();
        } else {
          timerListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public Builder addTimerList(google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl value) {
        if (timerListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimerListIsMutable();
          timerList_.add(value);
          onChanged();
        } else {
          timerListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public Builder addTimerList(
          int index, google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl value) {
        if (timerListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimerListIsMutable();
          timerList_.add(index, value);
          onChanged();
        } else {
          timerListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public Builder addTimerList(
          google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl.Builder builderForValue) {
        if (timerListBuilder_ == null) {
          ensureTimerListIsMutable();
          timerList_.add(builderForValue.build());
          onChanged();
        } else {
          timerListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public Builder addTimerList(
          int index, google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl.Builder builderForValue) {
        if (timerListBuilder_ == null) {
          ensureTimerListIsMutable();
          timerList_.add(index, builderForValue.build());
          onChanged();
        } else {
          timerListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public Builder addAllTimerList(
          java.lang.Iterable<? extends google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl> values) {
        if (timerListBuilder_ == null) {
          ensureTimerListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, timerList_);
          onChanged();
        } else {
          timerListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public Builder clearTimerList() {
        if (timerListBuilder_ == null) {
          timerList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          timerListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public Builder removeTimerList(int index) {
        if (timerListBuilder_ == null) {
          ensureTimerListIsMutable();
          timerList_.remove(index);
          onChanged();
        } else {
          timerListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl.Builder getTimerListBuilder(
          int index) {
        return getTimerListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public google.iproto.mqtt.SwsystimerctrlProto.timer_ctrlOrBuilder getTimerListOrBuilder(
          int index) {
        if (timerListBuilder_ == null) {
          return timerList_.get(index);  } else {
          return timerListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public java.util.List<? extends google.iproto.mqtt.SwsystimerctrlProto.timer_ctrlOrBuilder> 
           getTimerListOrBuilderList() {
        if (timerListBuilder_ != null) {
          return timerListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(timerList_);
        }
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl.Builder addTimerListBuilder() {
        return getTimerListFieldBuilder().addBuilder(
            google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl.getDefaultInstance());
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl.Builder addTimerListBuilder(
          int index) {
        return getTimerListFieldBuilder().addBuilder(
            index, google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl.getDefaultInstance());
      }
      /**
       * <pre>
       *定时器列表，每次将该场景所有定时器下发给设备侧
       * </pre>
       *
       * <code>repeated .google.iproto.timer_ctrl timer_list = 3;</code>
       */
      public java.util.List<google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl.Builder> 
           getTimerListBuilderList() {
        return getTimerListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl, google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl.Builder, google.iproto.mqtt.SwsystimerctrlProto.timer_ctrlOrBuilder> 
          getTimerListFieldBuilder() {
        if (timerListBuilder_ == null) {
          timerListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl, google.iproto.mqtt.SwsystimerctrlProto.timer_ctrl.Builder, google.iproto.mqtt.SwsystimerctrlProto.timer_ctrlOrBuilder>(
                  timerList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          timerList_ = null;
        }
        return timerListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:google.iproto.timer_operate)
    }

    // @@protoc_insertion_point(class_scope:google.iproto.timer_operate)
    private static final google.iproto.mqtt.SwsystimeropterateProto.timer_operate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new google.iproto.mqtt.SwsystimeropterateProto.timer_operate();
    }

    public static google.iproto.mqtt.SwsystimeropterateProto.timer_operate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<timer_operate>
        PARSER = new com.google.protobuf.AbstractParser<timer_operate>() {
      public timer_operate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new timer_operate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<timer_operate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<timer_operate> getParserForType() {
      return PARSER;
    }

    public google.iproto.mqtt.SwsystimeropterateProto.timer_operate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_iproto_timer_operate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_iproto_timer_operate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-google/iproto/mqtt/p0705_SwSys_timerop" +
      "t.proto\022\rgoogle.iproto\032.google/iproto/mq" +
      "tt/p0704_SwSys_timerctrl.proto\"a\n\rtimer_" +
      "operate\022\017\n\007systime\030\001 \001(\003\022\020\n\010timingid\030\002 \001" +
      "(\005\022-\n\ntimer_list\030\003 \003(\0132\031.google.iproto.t" +
      "imer_ctrlB-\n\022google.iproto.mqttB\027Swsysti" +
      "meropterateProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          google.iproto.mqtt.SwsystimerctrlProto.getDescriptor(),
        }, assigner);
    internal_static_google_iproto_timer_operate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_iproto_timer_operate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_iproto_timer_operate_descriptor,
        new java.lang.String[] { "Systime", "Timingid", "TimerList", });
    google.iproto.mqtt.SwsystimerctrlProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
