// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/iproto/device/GatewayStatusReq.proto

package google.iproto.device;

public final class GatewayStatusReqProto {
  private GatewayStatusReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GatewayStatusReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.iproto.GatewayStatusReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *家庭ID
     * </pre>
     *
     * <code>int32 homeid = 1;</code>
     */
    int getHomeid();
  }
  /**
   * <pre>
   *请求获取绑定Wifi是否成功
   * </pre>
   *
   * Protobuf type {@code google.iproto.GatewayStatusReq}
   */
  public  static final class GatewayStatusReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.iproto.GatewayStatusReq)
      GatewayStatusReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GatewayStatusReq.newBuilder() to construct.
    private GatewayStatusReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GatewayStatusReq() {
      homeid_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GatewayStatusReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              homeid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.iproto.device.GatewayStatusReqProto.internal_static_google_iproto_GatewayStatusReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.iproto.device.GatewayStatusReqProto.internal_static_google_iproto_GatewayStatusReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.iproto.device.GatewayStatusReqProto.GatewayStatusReq.class, google.iproto.device.GatewayStatusReqProto.GatewayStatusReq.Builder.class);
    }

    public static final int HOMEID_FIELD_NUMBER = 1;
    private int homeid_;
    /**
     * <pre>
     *家庭ID
     * </pre>
     *
     * <code>int32 homeid = 1;</code>
     */
    public int getHomeid() {
      return homeid_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (homeid_ != 0) {
        output.writeInt32(1, homeid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (homeid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, homeid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof google.iproto.device.GatewayStatusReqProto.GatewayStatusReq)) {
        return super.equals(obj);
      }
      google.iproto.device.GatewayStatusReqProto.GatewayStatusReq other = (google.iproto.device.GatewayStatusReqProto.GatewayStatusReq) obj;

      boolean result = true;
      result = result && (getHomeid()
          == other.getHomeid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HOMEID_FIELD_NUMBER;
      hash = (53 * hash) + getHomeid();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static google.iproto.device.GatewayStatusReqProto.GatewayStatusReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.device.GatewayStatusReqProto.GatewayStatusReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.device.GatewayStatusReqProto.GatewayStatusReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.device.GatewayStatusReqProto.GatewayStatusReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.device.GatewayStatusReqProto.GatewayStatusReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.device.GatewayStatusReqProto.GatewayStatusReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.device.GatewayStatusReqProto.GatewayStatusReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.iproto.device.GatewayStatusReqProto.GatewayStatusReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.iproto.device.GatewayStatusReqProto.GatewayStatusReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static google.iproto.device.GatewayStatusReqProto.GatewayStatusReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.iproto.device.GatewayStatusReqProto.GatewayStatusReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.iproto.device.GatewayStatusReqProto.GatewayStatusReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(google.iproto.device.GatewayStatusReqProto.GatewayStatusReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求获取绑定Wifi是否成功
     * </pre>
     *
     * Protobuf type {@code google.iproto.GatewayStatusReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.iproto.GatewayStatusReq)
        google.iproto.device.GatewayStatusReqProto.GatewayStatusReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.iproto.device.GatewayStatusReqProto.internal_static_google_iproto_GatewayStatusReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.iproto.device.GatewayStatusReqProto.internal_static_google_iproto_GatewayStatusReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                google.iproto.device.GatewayStatusReqProto.GatewayStatusReq.class, google.iproto.device.GatewayStatusReqProto.GatewayStatusReq.Builder.class);
      }

      // Construct using google.iproto.device.GatewayStatusReqProto.GatewayStatusReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        homeid_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.iproto.device.GatewayStatusReqProto.internal_static_google_iproto_GatewayStatusReq_descriptor;
      }

      public google.iproto.device.GatewayStatusReqProto.GatewayStatusReq getDefaultInstanceForType() {
        return google.iproto.device.GatewayStatusReqProto.GatewayStatusReq.getDefaultInstance();
      }

      public google.iproto.device.GatewayStatusReqProto.GatewayStatusReq build() {
        google.iproto.device.GatewayStatusReqProto.GatewayStatusReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public google.iproto.device.GatewayStatusReqProto.GatewayStatusReq buildPartial() {
        google.iproto.device.GatewayStatusReqProto.GatewayStatusReq result = new google.iproto.device.GatewayStatusReqProto.GatewayStatusReq(this);
        result.homeid_ = homeid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.iproto.device.GatewayStatusReqProto.GatewayStatusReq) {
          return mergeFrom((google.iproto.device.GatewayStatusReqProto.GatewayStatusReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(google.iproto.device.GatewayStatusReqProto.GatewayStatusReq other) {
        if (other == google.iproto.device.GatewayStatusReqProto.GatewayStatusReq.getDefaultInstance()) return this;
        if (other.getHomeid() != 0) {
          setHomeid(other.getHomeid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        google.iproto.device.GatewayStatusReqProto.GatewayStatusReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (google.iproto.device.GatewayStatusReqProto.GatewayStatusReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int homeid_ ;
      /**
       * <pre>
       *家庭ID
       * </pre>
       *
       * <code>int32 homeid = 1;</code>
       */
      public int getHomeid() {
        return homeid_;
      }
      /**
       * <pre>
       *家庭ID
       * </pre>
       *
       * <code>int32 homeid = 1;</code>
       */
      public Builder setHomeid(int value) {
        
        homeid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *家庭ID
       * </pre>
       *
       * <code>int32 homeid = 1;</code>
       */
      public Builder clearHomeid() {
        
        homeid_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:google.iproto.GatewayStatusReq)
    }

    // @@protoc_insertion_point(class_scope:google.iproto.GatewayStatusReq)
    private static final google.iproto.device.GatewayStatusReqProto.GatewayStatusReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new google.iproto.device.GatewayStatusReqProto.GatewayStatusReq();
    }

    public static google.iproto.device.GatewayStatusReqProto.GatewayStatusReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GatewayStatusReq>
        PARSER = new com.google.protobuf.AbstractParser<GatewayStatusReq>() {
      public GatewayStatusReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GatewayStatusReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GatewayStatusReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GatewayStatusReq> getParserForType() {
      return PARSER;
    }

    public google.iproto.device.GatewayStatusReqProto.GatewayStatusReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_iproto_GatewayStatusReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_iproto_GatewayStatusReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+google/iproto/device/GatewayStatusReq." +
      "proto\022\rgoogle.iproto\"\"\n\020GatewayStatusReq" +
      "\022\016\n\006homeid\030\001 \001(\005B-\n\024google.iproto.device" +
      "B\025GatewayStatusReqProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_google_iproto_GatewayStatusReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_iproto_GatewayStatusReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_iproto_GatewayStatusReq_descriptor,
        new java.lang.String[] { "Homeid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
