// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/iproto/scene/SceneToSensorListReq.proto

package google.iproto.scene;

public final class SceneToSensorListReqProto {
  private SceneToSensorListReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SceneToSensorListReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.iproto.SceneToSensorListReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sceneid = 1;</code>
     */
    int getSceneid();
  }
  /**
   * Protobuf type {@code google.iproto.SceneToSensorListReq}
   */
  public  static final class SceneToSensorListReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.iproto.SceneToSensorListReq)
      SceneToSensorListReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SceneToSensorListReq.newBuilder() to construct.
    private SceneToSensorListReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SceneToSensorListReq() {
      sceneid_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SceneToSensorListReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              sceneid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.iproto.scene.SceneToSensorListReqProto.internal_static_google_iproto_SceneToSensorListReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.iproto.scene.SceneToSensorListReqProto.internal_static_google_iproto_SceneToSensorListReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq.class, google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq.Builder.class);
    }

    public static final int SCENEID_FIELD_NUMBER = 1;
    private int sceneid_;
    /**
     * <code>int32 sceneid = 1;</code>
     */
    public int getSceneid() {
      return sceneid_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sceneid_ != 0) {
        output.writeInt32(1, sceneid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sceneid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sceneid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq)) {
        return super.equals(obj);
      }
      google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq other = (google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq) obj;

      boolean result = true;
      result = result && (getSceneid()
          == other.getSceneid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCENEID_FIELD_NUMBER;
      hash = (53 * hash) + getSceneid();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code google.iproto.SceneToSensorListReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.iproto.SceneToSensorListReq)
        google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.iproto.scene.SceneToSensorListReqProto.internal_static_google_iproto_SceneToSensorListReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.iproto.scene.SceneToSensorListReqProto.internal_static_google_iproto_SceneToSensorListReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq.class, google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq.Builder.class);
      }

      // Construct using google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sceneid_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.iproto.scene.SceneToSensorListReqProto.internal_static_google_iproto_SceneToSensorListReq_descriptor;
      }

      public google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq getDefaultInstanceForType() {
        return google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq.getDefaultInstance();
      }

      public google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq build() {
        google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq buildPartial() {
        google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq result = new google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq(this);
        result.sceneid_ = sceneid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq) {
          return mergeFrom((google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq other) {
        if (other == google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq.getDefaultInstance()) return this;
        if (other.getSceneid() != 0) {
          setSceneid(other.getSceneid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sceneid_ ;
      /**
       * <code>int32 sceneid = 1;</code>
       */
      public int getSceneid() {
        return sceneid_;
      }
      /**
       * <code>int32 sceneid = 1;</code>
       */
      public Builder setSceneid(int value) {
        
        sceneid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sceneid = 1;</code>
       */
      public Builder clearSceneid() {
        
        sceneid_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:google.iproto.SceneToSensorListReq)
    }

    // @@protoc_insertion_point(class_scope:google.iproto.SceneToSensorListReq)
    private static final google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq();
    }

    public static google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SceneToSensorListReq>
        PARSER = new com.google.protobuf.AbstractParser<SceneToSensorListReq>() {
      public SceneToSensorListReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SceneToSensorListReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SceneToSensorListReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SceneToSensorListReq> getParserForType() {
      return PARSER;
    }

    public google.iproto.scene.SceneToSensorListReqProto.SceneToSensorListReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_iproto_SceneToSensorListReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_iproto_SceneToSensorListReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.google/iproto/scene/SceneToSensorListR" +
      "eq.proto\022\rgoogle.iproto\"\'\n\024SceneToSensor" +
      "ListReq\022\017\n\007sceneid\030\001 \001(\005B0\n\023google.iprot" +
      "o.sceneB\031SceneToSensorListReqProtob\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_google_iproto_SceneToSensorListReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_iproto_SceneToSensorListReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_iproto_SceneToSensorListReq_descriptor,
        new java.lang.String[] { "Sceneid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
