// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/iproto/scene/SceneToMagnetPostReq.proto

package google.iproto.scene;

public final class SceneToMagnetPostReqProto {
  private SceneToMagnetPostReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SceneToMagnetPostReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.iproto.SceneToMagnetPostReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *场景ID
     * </pre>
     *
     * <code>int32 sceneid = 1;</code>
     */
    int getSceneid();

    /**
     * <pre>
     *门磁ID 集合
     * </pre>
     *
     * <code>repeated int32 magnetid = 2;</code>
     */
    java.util.List<java.lang.Integer> getMagnetidList();
    /**
     * <pre>
     *门磁ID 集合
     * </pre>
     *
     * <code>repeated int32 magnetid = 2;</code>
     */
    int getMagnetidCount();
    /**
     * <pre>
     *门磁ID 集合
     * </pre>
     *
     * <code>repeated int32 magnetid = 2;</code>
     */
    int getMagnetid(int index);
  }
  /**
   * <pre>
   *绑定场景到门磁获取门磁列表
   * </pre>
   *
   * Protobuf type {@code google.iproto.SceneToMagnetPostReq}
   */
  public  static final class SceneToMagnetPostReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.iproto.SceneToMagnetPostReq)
      SceneToMagnetPostReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SceneToMagnetPostReq.newBuilder() to construct.
    private SceneToMagnetPostReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SceneToMagnetPostReq() {
      sceneid_ = 0;
      magnetid_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SceneToMagnetPostReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              sceneid_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                magnetid_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              magnetid_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                magnetid_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                magnetid_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          magnetid_ = java.util.Collections.unmodifiableList(magnetid_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.iproto.scene.SceneToMagnetPostReqProto.internal_static_google_iproto_SceneToMagnetPostReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.iproto.scene.SceneToMagnetPostReqProto.internal_static_google_iproto_SceneToMagnetPostReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq.class, google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq.Builder.class);
    }

    private int bitField0_;
    public static final int SCENEID_FIELD_NUMBER = 1;
    private int sceneid_;
    /**
     * <pre>
     *场景ID
     * </pre>
     *
     * <code>int32 sceneid = 1;</code>
     */
    public int getSceneid() {
      return sceneid_;
    }

    public static final int MAGNETID_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> magnetid_;
    /**
     * <pre>
     *门磁ID 集合
     * </pre>
     *
     * <code>repeated int32 magnetid = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getMagnetidList() {
      return magnetid_;
    }
    /**
     * <pre>
     *门磁ID 集合
     * </pre>
     *
     * <code>repeated int32 magnetid = 2;</code>
     */
    public int getMagnetidCount() {
      return magnetid_.size();
    }
    /**
     * <pre>
     *门磁ID 集合
     * </pre>
     *
     * <code>repeated int32 magnetid = 2;</code>
     */
    public int getMagnetid(int index) {
      return magnetid_.get(index);
    }
    private int magnetidMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (sceneid_ != 0) {
        output.writeInt32(1, sceneid_);
      }
      if (getMagnetidList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(magnetidMemoizedSerializedSize);
      }
      for (int i = 0; i < magnetid_.size(); i++) {
        output.writeInt32NoTag(magnetid_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sceneid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sceneid_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < magnetid_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(magnetid_.get(i));
        }
        size += dataSize;
        if (!getMagnetidList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        magnetidMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq)) {
        return super.equals(obj);
      }
      google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq other = (google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq) obj;

      boolean result = true;
      result = result && (getSceneid()
          == other.getSceneid());
      result = result && getMagnetidList()
          .equals(other.getMagnetidList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCENEID_FIELD_NUMBER;
      hash = (53 * hash) + getSceneid();
      if (getMagnetidCount() > 0) {
        hash = (37 * hash) + MAGNETID_FIELD_NUMBER;
        hash = (53 * hash) + getMagnetidList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *绑定场景到门磁获取门磁列表
     * </pre>
     *
     * Protobuf type {@code google.iproto.SceneToMagnetPostReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.iproto.SceneToMagnetPostReq)
        google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.iproto.scene.SceneToMagnetPostReqProto.internal_static_google_iproto_SceneToMagnetPostReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.iproto.scene.SceneToMagnetPostReqProto.internal_static_google_iproto_SceneToMagnetPostReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq.class, google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq.Builder.class);
      }

      // Construct using google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sceneid_ = 0;

        magnetid_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.iproto.scene.SceneToMagnetPostReqProto.internal_static_google_iproto_SceneToMagnetPostReq_descriptor;
      }

      public google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq getDefaultInstanceForType() {
        return google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq.getDefaultInstance();
      }

      public google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq build() {
        google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq buildPartial() {
        google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq result = new google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.sceneid_ = sceneid_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          magnetid_ = java.util.Collections.unmodifiableList(magnetid_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.magnetid_ = magnetid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq) {
          return mergeFrom((google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq other) {
        if (other == google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq.getDefaultInstance()) return this;
        if (other.getSceneid() != 0) {
          setSceneid(other.getSceneid());
        }
        if (!other.magnetid_.isEmpty()) {
          if (magnetid_.isEmpty()) {
            magnetid_ = other.magnetid_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMagnetidIsMutable();
            magnetid_.addAll(other.magnetid_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int sceneid_ ;
      /**
       * <pre>
       *场景ID
       * </pre>
       *
       * <code>int32 sceneid = 1;</code>
       */
      public int getSceneid() {
        return sceneid_;
      }
      /**
       * <pre>
       *场景ID
       * </pre>
       *
       * <code>int32 sceneid = 1;</code>
       */
      public Builder setSceneid(int value) {
        
        sceneid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *场景ID
       * </pre>
       *
       * <code>int32 sceneid = 1;</code>
       */
      public Builder clearSceneid() {
        
        sceneid_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> magnetid_ = java.util.Collections.emptyList();
      private void ensureMagnetidIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          magnetid_ = new java.util.ArrayList<java.lang.Integer>(magnetid_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       *门磁ID 集合
       * </pre>
       *
       * <code>repeated int32 magnetid = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getMagnetidList() {
        return java.util.Collections.unmodifiableList(magnetid_);
      }
      /**
       * <pre>
       *门磁ID 集合
       * </pre>
       *
       * <code>repeated int32 magnetid = 2;</code>
       */
      public int getMagnetidCount() {
        return magnetid_.size();
      }
      /**
       * <pre>
       *门磁ID 集合
       * </pre>
       *
       * <code>repeated int32 magnetid = 2;</code>
       */
      public int getMagnetid(int index) {
        return magnetid_.get(index);
      }
      /**
       * <pre>
       *门磁ID 集合
       * </pre>
       *
       * <code>repeated int32 magnetid = 2;</code>
       */
      public Builder setMagnetid(
          int index, int value) {
        ensureMagnetidIsMutable();
        magnetid_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *门磁ID 集合
       * </pre>
       *
       * <code>repeated int32 magnetid = 2;</code>
       */
      public Builder addMagnetid(int value) {
        ensureMagnetidIsMutable();
        magnetid_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *门磁ID 集合
       * </pre>
       *
       * <code>repeated int32 magnetid = 2;</code>
       */
      public Builder addAllMagnetid(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureMagnetidIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, magnetid_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *门磁ID 集合
       * </pre>
       *
       * <code>repeated int32 magnetid = 2;</code>
       */
      public Builder clearMagnetid() {
        magnetid_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:google.iproto.SceneToMagnetPostReq)
    }

    // @@protoc_insertion_point(class_scope:google.iproto.SceneToMagnetPostReq)
    private static final google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq();
    }

    public static google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SceneToMagnetPostReq>
        PARSER = new com.google.protobuf.AbstractParser<SceneToMagnetPostReq>() {
      public SceneToMagnetPostReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SceneToMagnetPostReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SceneToMagnetPostReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SceneToMagnetPostReq> getParserForType() {
      return PARSER;
    }

    public google.iproto.scene.SceneToMagnetPostReqProto.SceneToMagnetPostReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_iproto_SceneToMagnetPostReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_iproto_SceneToMagnetPostReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.google/iproto/scene/SceneToMagnetPostR" +
      "eq.proto\022\rgoogle.iproto\"9\n\024SceneToMagnet" +
      "PostReq\022\017\n\007sceneid\030\001 \001(\005\022\020\n\010magnetid\030\002 \003" +
      "(\005B0\n\023google.iproto.sceneB\031SceneToMagnet" +
      "PostReqProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_google_iproto_SceneToMagnetPostReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_iproto_SceneToMagnetPostReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_iproto_SceneToMagnetPostReq_descriptor,
        new java.lang.String[] { "Sceneid", "Magnetid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
