// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/iproto/login/LoginRes.proto

package google.iproto.login;

public final class LoginResProto {
  private LoginResProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.iproto.LoginRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户ID（唯一）
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    java.lang.String getUuid();
    /**
     * <pre>
     *用户ID（唯一）
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     *用户昵称
     * </pre>
     *
     * <code>string nickname = 3;</code>
     */
    java.lang.String getNickname();
    /**
     * <pre>
     *用户昵称
     * </pre>
     *
     * <code>string nickname = 3;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>string gender = 4;</code>
     */
    java.lang.String getGender();
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>string gender = 4;</code>
     */
    com.google.protobuf.ByteString
        getGenderBytes();

    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>string address = 5;</code>
     */
    java.lang.String getAddress();
    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>string address = 5;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <pre>
     *用户头像地址
     * </pre>
     *
     * <code>string headurl = 6;</code>
     */
    java.lang.String getHeadurl();
    /**
     * <pre>
     *用户头像地址
     * </pre>
     *
     * <code>string headurl = 6;</code>
     */
    com.google.protobuf.ByteString
        getHeadurlBytes();

    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>string tel = 7;</code>
     */
    java.lang.String getTel();
    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>string tel = 7;</code>
     */
    com.google.protobuf.ByteString
        getTelBytes();

    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>int32 homeid = 8;</code>
     */
    int getHomeid();

    /**
     * <pre>
     *用户Mqtt productKey
     * </pre>
     *
     * <code>string user_productKey = 9;</code>
     */
    java.lang.String getUserProductKey();
    /**
     * <pre>
     *用户Mqtt productKey
     * </pre>
     *
     * <code>string user_productKey = 9;</code>
     */
    com.google.protobuf.ByteString
        getUserProductKeyBytes();

    /**
     * <pre>
     *用户Mqtt deviceName
     * </pre>
     *
     * <code>string user_deviceName = 10;</code>
     */
    java.lang.String getUserDeviceName();
    /**
     * <pre>
     *用户Mqtt deviceName
     * </pre>
     *
     * <code>string user_deviceName = 10;</code>
     */
    com.google.protobuf.ByteString
        getUserDeviceNameBytes();

    /**
     * <pre>
     *用户Mqtt deviceSecret
     * </pre>
     *
     * <code>string user_deviceSecret = 11;</code>
     */
    java.lang.String getUserDeviceSecret();
    /**
     * <pre>
     *用户Mqtt deviceSecret
     * </pre>
     *
     * <code>string user_deviceSecret = 11;</code>
     */
    com.google.protobuf.ByteString
        getUserDeviceSecretBytes();

    /**
     * <pre>
     *网关Mqtt productKey
     * </pre>
     *
     * <code>string gateway_productKey = 12;</code>
     */
    java.lang.String getGatewayProductKey();
    /**
     * <pre>
     *网关Mqtt productKey
     * </pre>
     *
     * <code>string gateway_productKey = 12;</code>
     */
    com.google.protobuf.ByteString
        getGatewayProductKeyBytes();

    /**
     * <pre>
     *网关Mqtt deviceName
     * </pre>
     *
     * <code>string gateway_deviceName = 13;</code>
     */
    java.lang.String getGatewayDeviceName();
    /**
     * <pre>
     *网关Mqtt deviceName
     * </pre>
     *
     * <code>string gateway_deviceName = 13;</code>
     */
    com.google.protobuf.ByteString
        getGatewayDeviceNameBytes();

    /**
     * <pre>
     *网关Mqtt deviceSecret
     * </pre>
     *
     * <code>string gateway_deviceSecret = 14;</code>
     */
    java.lang.String getGatewayDeviceSecret();
    /**
     * <pre>
     *网关Mqtt deviceSecret
     * </pre>
     *
     * <code>string gateway_deviceSecret = 14;</code>
     */
    com.google.protobuf.ByteString
        getGatewayDeviceSecretBytes();

    /**
     * <pre>
     *用户用TOKEN
     * </pre>
     *
     * <code>string at = 15;</code>
     */
    java.lang.String getAt();
    /**
     * <pre>
     *用户用TOKEN
     * </pre>
     *
     * <code>string at = 15;</code>
     */
    com.google.protobuf.ByteString
        getAtBytes();

    /**
     * <pre>
     *服务器Mqtt deviceSecret
     * </pre>
     *
     * <code>string service_deviceName = 16;</code>
     */
    java.lang.String getServiceDeviceName();
    /**
     * <pre>
     *服务器Mqtt deviceSecret
     * </pre>
     *
     * <code>string service_deviceName = 16;</code>
     */
    com.google.protobuf.ByteString
        getServiceDeviceNameBytes();

    /**
     * <pre>
     *用户类型直接返回用户类型，列：master, member,engineer
     * </pre>
     *
     * <code>string usertype = 17;</code>
     */
    java.lang.String getUsertype();
    /**
     * <pre>
     *用户类型直接返回用户类型，列：master, member,engineer
     * </pre>
     *
     * <code>string usertype = 17;</code>
     */
    com.google.protobuf.ByteString
        getUsertypeBytes();

    /**
     * <pre>
     *home下面所有用户的iot信息
     * </pre>
     *
     * <code>repeated string app_iots = 18;</code>
     */
    java.util.List<java.lang.String>
        getAppIotsList();
    /**
     * <pre>
     *home下面所有用户的iot信息
     * </pre>
     *
     * <code>repeated string app_iots = 18;</code>
     */
    int getAppIotsCount();
    /**
     * <pre>
     *home下面所有用户的iot信息
     * </pre>
     *
     * <code>repeated string app_iots = 18;</code>
     */
    java.lang.String getAppIots(int index);
    /**
     * <pre>
     *home下面所有用户的iot信息
     * </pre>
     *
     * <code>repeated string app_iots = 18;</code>
     */
    com.google.protobuf.ByteString
        getAppIotsBytes(int index);
  }
  /**
   * <pre>
   *登录响应
   * </pre>
   *
   * Protobuf type {@code google.iproto.LoginRes}
   */
  public  static final class LoginRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.iproto.LoginRes)
      LoginResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginRes.newBuilder() to construct.
    private LoginRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginRes() {
      uuid_ = "";
      token_ = "";
      nickname_ = "";
      gender_ = "";
      address_ = "";
      headurl_ = "";
      tel_ = "";
      homeid_ = 0;
      userProductKey_ = "";
      userDeviceName_ = "";
      userDeviceSecret_ = "";
      gatewayProductKey_ = "";
      gatewayDeviceName_ = "";
      gatewayDeviceSecret_ = "";
      at_ = "";
      serviceDeviceName_ = "";
      usertype_ = "";
      appIots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uuid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              nickname_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              gender_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              headurl_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              tel_ = s;
              break;
            }
            case 64: {

              homeid_ = input.readInt32();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              userProductKey_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              userDeviceName_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              userDeviceSecret_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              gatewayProductKey_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              gatewayDeviceName_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              gatewayDeviceSecret_ = s;
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              at_ = s;
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              serviceDeviceName_ = s;
              break;
            }
            case 138: {
              java.lang.String s = input.readStringRequireUtf8();

              usertype_ = s;
              break;
            }
            case 146: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00020000) == 0x00020000)) {
                appIots_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00020000;
              }
              appIots_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00020000) == 0x00020000)) {
          appIots_ = appIots_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.iproto.login.LoginResProto.internal_static_google_iproto_LoginRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.iproto.login.LoginResProto.internal_static_google_iproto_LoginRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.iproto.login.LoginResProto.LoginRes.class, google.iproto.login.LoginResProto.LoginRes.Builder.class);
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <pre>
     *用户ID（唯一）
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户ID（唯一）
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object nickname_;
    /**
     * <pre>
     *用户昵称
     * </pre>
     *
     * <code>string nickname = 3;</code>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickname_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户昵称
     * </pre>
     *
     * <code>string nickname = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 4;
    private volatile java.lang.Object gender_;
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>string gender = 4;</code>
     */
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gender_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>string gender = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private volatile java.lang.Object address_;
    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>string address = 5;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>string address = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADURL_FIELD_NUMBER = 6;
    private volatile java.lang.Object headurl_;
    /**
     * <pre>
     *用户头像地址
     * </pre>
     *
     * <code>string headurl = 6;</code>
     */
    public java.lang.String getHeadurl() {
      java.lang.Object ref = headurl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        headurl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户头像地址
     * </pre>
     *
     * <code>string headurl = 6;</code>
     */
    public com.google.protobuf.ByteString
        getHeadurlBytes() {
      java.lang.Object ref = headurl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headurl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEL_FIELD_NUMBER = 7;
    private volatile java.lang.Object tel_;
    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>string tel = 7;</code>
     */
    public java.lang.String getTel() {
      java.lang.Object ref = tel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tel_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>string tel = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTelBytes() {
      java.lang.Object ref = tel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOMEID_FIELD_NUMBER = 8;
    private int homeid_;
    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>int32 homeid = 8;</code>
     */
    public int getHomeid() {
      return homeid_;
    }

    public static final int USER_PRODUCTKEY_FIELD_NUMBER = 9;
    private volatile java.lang.Object userProductKey_;
    /**
     * <pre>
     *用户Mqtt productKey
     * </pre>
     *
     * <code>string user_productKey = 9;</code>
     */
    public java.lang.String getUserProductKey() {
      java.lang.Object ref = userProductKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userProductKey_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户Mqtt productKey
     * </pre>
     *
     * <code>string user_productKey = 9;</code>
     */
    public com.google.protobuf.ByteString
        getUserProductKeyBytes() {
      java.lang.Object ref = userProductKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userProductKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_DEVICENAME_FIELD_NUMBER = 10;
    private volatile java.lang.Object userDeviceName_;
    /**
     * <pre>
     *用户Mqtt deviceName
     * </pre>
     *
     * <code>string user_deviceName = 10;</code>
     */
    public java.lang.String getUserDeviceName() {
      java.lang.Object ref = userDeviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userDeviceName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户Mqtt deviceName
     * </pre>
     *
     * <code>string user_deviceName = 10;</code>
     */
    public com.google.protobuf.ByteString
        getUserDeviceNameBytes() {
      java.lang.Object ref = userDeviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userDeviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_DEVICESECRET_FIELD_NUMBER = 11;
    private volatile java.lang.Object userDeviceSecret_;
    /**
     * <pre>
     *用户Mqtt deviceSecret
     * </pre>
     *
     * <code>string user_deviceSecret = 11;</code>
     */
    public java.lang.String getUserDeviceSecret() {
      java.lang.Object ref = userDeviceSecret_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userDeviceSecret_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户Mqtt deviceSecret
     * </pre>
     *
     * <code>string user_deviceSecret = 11;</code>
     */
    public com.google.protobuf.ByteString
        getUserDeviceSecretBytes() {
      java.lang.Object ref = userDeviceSecret_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userDeviceSecret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GATEWAY_PRODUCTKEY_FIELD_NUMBER = 12;
    private volatile java.lang.Object gatewayProductKey_;
    /**
     * <pre>
     *网关Mqtt productKey
     * </pre>
     *
     * <code>string gateway_productKey = 12;</code>
     */
    public java.lang.String getGatewayProductKey() {
      java.lang.Object ref = gatewayProductKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gatewayProductKey_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *网关Mqtt productKey
     * </pre>
     *
     * <code>string gateway_productKey = 12;</code>
     */
    public com.google.protobuf.ByteString
        getGatewayProductKeyBytes() {
      java.lang.Object ref = gatewayProductKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gatewayProductKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GATEWAY_DEVICENAME_FIELD_NUMBER = 13;
    private volatile java.lang.Object gatewayDeviceName_;
    /**
     * <pre>
     *网关Mqtt deviceName
     * </pre>
     *
     * <code>string gateway_deviceName = 13;</code>
     */
    public java.lang.String getGatewayDeviceName() {
      java.lang.Object ref = gatewayDeviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gatewayDeviceName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *网关Mqtt deviceName
     * </pre>
     *
     * <code>string gateway_deviceName = 13;</code>
     */
    public com.google.protobuf.ByteString
        getGatewayDeviceNameBytes() {
      java.lang.Object ref = gatewayDeviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gatewayDeviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GATEWAY_DEVICESECRET_FIELD_NUMBER = 14;
    private volatile java.lang.Object gatewayDeviceSecret_;
    /**
     * <pre>
     *网关Mqtt deviceSecret
     * </pre>
     *
     * <code>string gateway_deviceSecret = 14;</code>
     */
    public java.lang.String getGatewayDeviceSecret() {
      java.lang.Object ref = gatewayDeviceSecret_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gatewayDeviceSecret_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *网关Mqtt deviceSecret
     * </pre>
     *
     * <code>string gateway_deviceSecret = 14;</code>
     */
    public com.google.protobuf.ByteString
        getGatewayDeviceSecretBytes() {
      java.lang.Object ref = gatewayDeviceSecret_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gatewayDeviceSecret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AT_FIELD_NUMBER = 15;
    private volatile java.lang.Object at_;
    /**
     * <pre>
     *用户用TOKEN
     * </pre>
     *
     * <code>string at = 15;</code>
     */
    public java.lang.String getAt() {
      java.lang.Object ref = at_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        at_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户用TOKEN
     * </pre>
     *
     * <code>string at = 15;</code>
     */
    public com.google.protobuf.ByteString
        getAtBytes() {
      java.lang.Object ref = at_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        at_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICE_DEVICENAME_FIELD_NUMBER = 16;
    private volatile java.lang.Object serviceDeviceName_;
    /**
     * <pre>
     *服务器Mqtt deviceSecret
     * </pre>
     *
     * <code>string service_deviceName = 16;</code>
     */
    public java.lang.String getServiceDeviceName() {
      java.lang.Object ref = serviceDeviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceDeviceName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *服务器Mqtt deviceSecret
     * </pre>
     *
     * <code>string service_deviceName = 16;</code>
     */
    public com.google.protobuf.ByteString
        getServiceDeviceNameBytes() {
      java.lang.Object ref = serviceDeviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceDeviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERTYPE_FIELD_NUMBER = 17;
    private volatile java.lang.Object usertype_;
    /**
     * <pre>
     *用户类型直接返回用户类型，列：master, member,engineer
     * </pre>
     *
     * <code>string usertype = 17;</code>
     */
    public java.lang.String getUsertype() {
      java.lang.Object ref = usertype_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        usertype_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户类型直接返回用户类型，列：master, member,engineer
     * </pre>
     *
     * <code>string usertype = 17;</code>
     */
    public com.google.protobuf.ByteString
        getUsertypeBytes() {
      java.lang.Object ref = usertype_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usertype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_IOTS_FIELD_NUMBER = 18;
    private com.google.protobuf.LazyStringList appIots_;
    /**
     * <pre>
     *home下面所有用户的iot信息
     * </pre>
     *
     * <code>repeated string app_iots = 18;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAppIotsList() {
      return appIots_;
    }
    /**
     * <pre>
     *home下面所有用户的iot信息
     * </pre>
     *
     * <code>repeated string app_iots = 18;</code>
     */
    public int getAppIotsCount() {
      return appIots_.size();
    }
    /**
     * <pre>
     *home下面所有用户的iot信息
     * </pre>
     *
     * <code>repeated string app_iots = 18;</code>
     */
    public java.lang.String getAppIots(int index) {
      return appIots_.get(index);
    }
    /**
     * <pre>
     *home下面所有用户的iot信息
     * </pre>
     *
     * <code>repeated string app_iots = 18;</code>
     */
    public com.google.protobuf.ByteString
        getAppIotsBytes(int index) {
      return appIots_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      if (!getNicknameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nickname_);
      }
      if (!getGenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, gender_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
      }
      if (!getHeadurlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, headurl_);
      }
      if (!getTelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, tel_);
      }
      if (homeid_ != 0) {
        output.writeInt32(8, homeid_);
      }
      if (!getUserProductKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, userProductKey_);
      }
      if (!getUserDeviceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, userDeviceName_);
      }
      if (!getUserDeviceSecretBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, userDeviceSecret_);
      }
      if (!getGatewayProductKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, gatewayProductKey_);
      }
      if (!getGatewayDeviceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, gatewayDeviceName_);
      }
      if (!getGatewayDeviceSecretBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, gatewayDeviceSecret_);
      }
      if (!getAtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, at_);
      }
      if (!getServiceDeviceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, serviceDeviceName_);
      }
      if (!getUsertypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 17, usertype_);
      }
      for (int i = 0; i < appIots_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 18, appIots_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      if (!getNicknameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nickname_);
      }
      if (!getGenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, gender_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
      }
      if (!getHeadurlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, headurl_);
      }
      if (!getTelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, tel_);
      }
      if (homeid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, homeid_);
      }
      if (!getUserProductKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, userProductKey_);
      }
      if (!getUserDeviceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, userDeviceName_);
      }
      if (!getUserDeviceSecretBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, userDeviceSecret_);
      }
      if (!getGatewayProductKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, gatewayProductKey_);
      }
      if (!getGatewayDeviceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, gatewayDeviceName_);
      }
      if (!getGatewayDeviceSecretBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, gatewayDeviceSecret_);
      }
      if (!getAtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, at_);
      }
      if (!getServiceDeviceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, serviceDeviceName_);
      }
      if (!getUsertypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, usertype_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < appIots_.size(); i++) {
          dataSize += computeStringSizeNoTag(appIots_.getRaw(i));
        }
        size += dataSize;
        size += 2 * getAppIotsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof google.iproto.login.LoginResProto.LoginRes)) {
        return super.equals(obj);
      }
      google.iproto.login.LoginResProto.LoginRes other = (google.iproto.login.LoginResProto.LoginRes) obj;

      boolean result = true;
      result = result && getUuid()
          .equals(other.getUuid());
      result = result && getToken()
          .equals(other.getToken());
      result = result && getNickname()
          .equals(other.getNickname());
      result = result && getGender()
          .equals(other.getGender());
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && getHeadurl()
          .equals(other.getHeadurl());
      result = result && getTel()
          .equals(other.getTel());
      result = result && (getHomeid()
          == other.getHomeid());
      result = result && getUserProductKey()
          .equals(other.getUserProductKey());
      result = result && getUserDeviceName()
          .equals(other.getUserDeviceName());
      result = result && getUserDeviceSecret()
          .equals(other.getUserDeviceSecret());
      result = result && getGatewayProductKey()
          .equals(other.getGatewayProductKey());
      result = result && getGatewayDeviceName()
          .equals(other.getGatewayDeviceName());
      result = result && getGatewayDeviceSecret()
          .equals(other.getGatewayDeviceSecret());
      result = result && getAt()
          .equals(other.getAt());
      result = result && getServiceDeviceName()
          .equals(other.getServiceDeviceName());
      result = result && getUsertype()
          .equals(other.getUsertype());
      result = result && getAppIotsList()
          .equals(other.getAppIotsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickname().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + HEADURL_FIELD_NUMBER;
      hash = (53 * hash) + getHeadurl().hashCode();
      hash = (37 * hash) + TEL_FIELD_NUMBER;
      hash = (53 * hash) + getTel().hashCode();
      hash = (37 * hash) + HOMEID_FIELD_NUMBER;
      hash = (53 * hash) + getHomeid();
      hash = (37 * hash) + USER_PRODUCTKEY_FIELD_NUMBER;
      hash = (53 * hash) + getUserProductKey().hashCode();
      hash = (37 * hash) + USER_DEVICENAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserDeviceName().hashCode();
      hash = (37 * hash) + USER_DEVICESECRET_FIELD_NUMBER;
      hash = (53 * hash) + getUserDeviceSecret().hashCode();
      hash = (37 * hash) + GATEWAY_PRODUCTKEY_FIELD_NUMBER;
      hash = (53 * hash) + getGatewayProductKey().hashCode();
      hash = (37 * hash) + GATEWAY_DEVICENAME_FIELD_NUMBER;
      hash = (53 * hash) + getGatewayDeviceName().hashCode();
      hash = (37 * hash) + GATEWAY_DEVICESECRET_FIELD_NUMBER;
      hash = (53 * hash) + getGatewayDeviceSecret().hashCode();
      hash = (37 * hash) + AT_FIELD_NUMBER;
      hash = (53 * hash) + getAt().hashCode();
      hash = (37 * hash) + SERVICE_DEVICENAME_FIELD_NUMBER;
      hash = (53 * hash) + getServiceDeviceName().hashCode();
      hash = (37 * hash) + USERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getUsertype().hashCode();
      if (getAppIotsCount() > 0) {
        hash = (37 * hash) + APP_IOTS_FIELD_NUMBER;
        hash = (53 * hash) + getAppIotsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static google.iproto.login.LoginResProto.LoginRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.login.LoginResProto.LoginRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.login.LoginResProto.LoginRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.login.LoginResProto.LoginRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.login.LoginResProto.LoginRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.iproto.login.LoginResProto.LoginRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.iproto.login.LoginResProto.LoginRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.iproto.login.LoginResProto.LoginRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.iproto.login.LoginResProto.LoginRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static google.iproto.login.LoginResProto.LoginRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.iproto.login.LoginResProto.LoginRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.iproto.login.LoginResProto.LoginRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(google.iproto.login.LoginResProto.LoginRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *登录响应
     * </pre>
     *
     * Protobuf type {@code google.iproto.LoginRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.iproto.LoginRes)
        google.iproto.login.LoginResProto.LoginResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.iproto.login.LoginResProto.internal_static_google_iproto_LoginRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.iproto.login.LoginResProto.internal_static_google_iproto_LoginRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                google.iproto.login.LoginResProto.LoginRes.class, google.iproto.login.LoginResProto.LoginRes.Builder.class);
      }

      // Construct using google.iproto.login.LoginResProto.LoginRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = "";

        token_ = "";

        nickname_ = "";

        gender_ = "";

        address_ = "";

        headurl_ = "";

        tel_ = "";

        homeid_ = 0;

        userProductKey_ = "";

        userDeviceName_ = "";

        userDeviceSecret_ = "";

        gatewayProductKey_ = "";

        gatewayDeviceName_ = "";

        gatewayDeviceSecret_ = "";

        at_ = "";

        serviceDeviceName_ = "";

        usertype_ = "";

        appIots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00020000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.iproto.login.LoginResProto.internal_static_google_iproto_LoginRes_descriptor;
      }

      public google.iproto.login.LoginResProto.LoginRes getDefaultInstanceForType() {
        return google.iproto.login.LoginResProto.LoginRes.getDefaultInstance();
      }

      public google.iproto.login.LoginResProto.LoginRes build() {
        google.iproto.login.LoginResProto.LoginRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public google.iproto.login.LoginResProto.LoginRes buildPartial() {
        google.iproto.login.LoginResProto.LoginRes result = new google.iproto.login.LoginResProto.LoginRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.uuid_ = uuid_;
        result.token_ = token_;
        result.nickname_ = nickname_;
        result.gender_ = gender_;
        result.address_ = address_;
        result.headurl_ = headurl_;
        result.tel_ = tel_;
        result.homeid_ = homeid_;
        result.userProductKey_ = userProductKey_;
        result.userDeviceName_ = userDeviceName_;
        result.userDeviceSecret_ = userDeviceSecret_;
        result.gatewayProductKey_ = gatewayProductKey_;
        result.gatewayDeviceName_ = gatewayDeviceName_;
        result.gatewayDeviceSecret_ = gatewayDeviceSecret_;
        result.at_ = at_;
        result.serviceDeviceName_ = serviceDeviceName_;
        result.usertype_ = usertype_;
        if (((bitField0_ & 0x00020000) == 0x00020000)) {
          appIots_ = appIots_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00020000);
        }
        result.appIots_ = appIots_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.iproto.login.LoginResProto.LoginRes) {
          return mergeFrom((google.iproto.login.LoginResProto.LoginRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(google.iproto.login.LoginResProto.LoginRes other) {
        if (other == google.iproto.login.LoginResProto.LoginRes.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (!other.getNickname().isEmpty()) {
          nickname_ = other.nickname_;
          onChanged();
        }
        if (!other.getGender().isEmpty()) {
          gender_ = other.gender_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getHeadurl().isEmpty()) {
          headurl_ = other.headurl_;
          onChanged();
        }
        if (!other.getTel().isEmpty()) {
          tel_ = other.tel_;
          onChanged();
        }
        if (other.getHomeid() != 0) {
          setHomeid(other.getHomeid());
        }
        if (!other.getUserProductKey().isEmpty()) {
          userProductKey_ = other.userProductKey_;
          onChanged();
        }
        if (!other.getUserDeviceName().isEmpty()) {
          userDeviceName_ = other.userDeviceName_;
          onChanged();
        }
        if (!other.getUserDeviceSecret().isEmpty()) {
          userDeviceSecret_ = other.userDeviceSecret_;
          onChanged();
        }
        if (!other.getGatewayProductKey().isEmpty()) {
          gatewayProductKey_ = other.gatewayProductKey_;
          onChanged();
        }
        if (!other.getGatewayDeviceName().isEmpty()) {
          gatewayDeviceName_ = other.gatewayDeviceName_;
          onChanged();
        }
        if (!other.getGatewayDeviceSecret().isEmpty()) {
          gatewayDeviceSecret_ = other.gatewayDeviceSecret_;
          onChanged();
        }
        if (!other.getAt().isEmpty()) {
          at_ = other.at_;
          onChanged();
        }
        if (!other.getServiceDeviceName().isEmpty()) {
          serviceDeviceName_ = other.serviceDeviceName_;
          onChanged();
        }
        if (!other.getUsertype().isEmpty()) {
          usertype_ = other.usertype_;
          onChanged();
        }
        if (!other.appIots_.isEmpty()) {
          if (appIots_.isEmpty()) {
            appIots_ = other.appIots_;
            bitField0_ = (bitField0_ & ~0x00020000);
          } else {
            ensureAppIotsIsMutable();
            appIots_.addAll(other.appIots_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        google.iproto.login.LoginResProto.LoginRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (google.iproto.login.LoginResProto.LoginRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uuid_ = "";
      /**
       * <pre>
       *用户ID（唯一）
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户ID（唯一）
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户ID（唯一）
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户ID（唯一）
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户ID（唯一）
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 2;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <pre>
       *用户昵称
       * </pre>
       *
       * <code>string nickname = 3;</code>
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户昵称
       * </pre>
       *
       * <code>string nickname = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户昵称
       * </pre>
       *
       * <code>string nickname = 3;</code>
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户昵称
       * </pre>
       *
       * <code>string nickname = 3;</code>
       */
      public Builder clearNickname() {
        
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户昵称
       * </pre>
       *
       * <code>string nickname = 3;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gender_ = "";
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>string gender = 4;</code>
       */
      public java.lang.String getGender() {
        java.lang.Object ref = gender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>string gender = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGenderBytes() {
        java.lang.Object ref = gender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>string gender = 4;</code>
       */
      public Builder setGender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>string gender = 4;</code>
       */
      public Builder clearGender() {
        
        gender_ = getDefaultInstance().getGender();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>string gender = 4;</code>
       */
      public Builder setGenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>string address = 5;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>string address = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>string address = 5;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>string address = 5;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>string address = 5;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object headurl_ = "";
      /**
       * <pre>
       *用户头像地址
       * </pre>
       *
       * <code>string headurl = 6;</code>
       */
      public java.lang.String getHeadurl() {
        java.lang.Object ref = headurl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          headurl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户头像地址
       * </pre>
       *
       * <code>string headurl = 6;</code>
       */
      public com.google.protobuf.ByteString
          getHeadurlBytes() {
        java.lang.Object ref = headurl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headurl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户头像地址
       * </pre>
       *
       * <code>string headurl = 6;</code>
       */
      public Builder setHeadurl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        headurl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户头像地址
       * </pre>
       *
       * <code>string headurl = 6;</code>
       */
      public Builder clearHeadurl() {
        
        headurl_ = getDefaultInstance().getHeadurl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户头像地址
       * </pre>
       *
       * <code>string headurl = 6;</code>
       */
      public Builder setHeadurlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        headurl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tel_ = "";
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>string tel = 7;</code>
       */
      public java.lang.String getTel() {
        java.lang.Object ref = tel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>string tel = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTelBytes() {
        java.lang.Object ref = tel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>string tel = 7;</code>
       */
      public Builder setTel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>string tel = 7;</code>
       */
      public Builder clearTel() {
        
        tel_ = getDefaultInstance().getTel();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>string tel = 7;</code>
       */
      public Builder setTelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tel_ = value;
        onChanged();
        return this;
      }

      private int homeid_ ;
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>int32 homeid = 8;</code>
       */
      public int getHomeid() {
        return homeid_;
      }
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>int32 homeid = 8;</code>
       */
      public Builder setHomeid(int value) {
        
        homeid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>int32 homeid = 8;</code>
       */
      public Builder clearHomeid() {
        
        homeid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userProductKey_ = "";
      /**
       * <pre>
       *用户Mqtt productKey
       * </pre>
       *
       * <code>string user_productKey = 9;</code>
       */
      public java.lang.String getUserProductKey() {
        java.lang.Object ref = userProductKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userProductKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户Mqtt productKey
       * </pre>
       *
       * <code>string user_productKey = 9;</code>
       */
      public com.google.protobuf.ByteString
          getUserProductKeyBytes() {
        java.lang.Object ref = userProductKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userProductKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户Mqtt productKey
       * </pre>
       *
       * <code>string user_productKey = 9;</code>
       */
      public Builder setUserProductKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userProductKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户Mqtt productKey
       * </pre>
       *
       * <code>string user_productKey = 9;</code>
       */
      public Builder clearUserProductKey() {
        
        userProductKey_ = getDefaultInstance().getUserProductKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户Mqtt productKey
       * </pre>
       *
       * <code>string user_productKey = 9;</code>
       */
      public Builder setUserProductKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userProductKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userDeviceName_ = "";
      /**
       * <pre>
       *用户Mqtt deviceName
       * </pre>
       *
       * <code>string user_deviceName = 10;</code>
       */
      public java.lang.String getUserDeviceName() {
        java.lang.Object ref = userDeviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userDeviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户Mqtt deviceName
       * </pre>
       *
       * <code>string user_deviceName = 10;</code>
       */
      public com.google.protobuf.ByteString
          getUserDeviceNameBytes() {
        java.lang.Object ref = userDeviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userDeviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户Mqtt deviceName
       * </pre>
       *
       * <code>string user_deviceName = 10;</code>
       */
      public Builder setUserDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userDeviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户Mqtt deviceName
       * </pre>
       *
       * <code>string user_deviceName = 10;</code>
       */
      public Builder clearUserDeviceName() {
        
        userDeviceName_ = getDefaultInstance().getUserDeviceName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户Mqtt deviceName
       * </pre>
       *
       * <code>string user_deviceName = 10;</code>
       */
      public Builder setUserDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userDeviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userDeviceSecret_ = "";
      /**
       * <pre>
       *用户Mqtt deviceSecret
       * </pre>
       *
       * <code>string user_deviceSecret = 11;</code>
       */
      public java.lang.String getUserDeviceSecret() {
        java.lang.Object ref = userDeviceSecret_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userDeviceSecret_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户Mqtt deviceSecret
       * </pre>
       *
       * <code>string user_deviceSecret = 11;</code>
       */
      public com.google.protobuf.ByteString
          getUserDeviceSecretBytes() {
        java.lang.Object ref = userDeviceSecret_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userDeviceSecret_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户Mqtt deviceSecret
       * </pre>
       *
       * <code>string user_deviceSecret = 11;</code>
       */
      public Builder setUserDeviceSecret(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userDeviceSecret_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户Mqtt deviceSecret
       * </pre>
       *
       * <code>string user_deviceSecret = 11;</code>
       */
      public Builder clearUserDeviceSecret() {
        
        userDeviceSecret_ = getDefaultInstance().getUserDeviceSecret();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户Mqtt deviceSecret
       * </pre>
       *
       * <code>string user_deviceSecret = 11;</code>
       */
      public Builder setUserDeviceSecretBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userDeviceSecret_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gatewayProductKey_ = "";
      /**
       * <pre>
       *网关Mqtt productKey
       * </pre>
       *
       * <code>string gateway_productKey = 12;</code>
       */
      public java.lang.String getGatewayProductKey() {
        java.lang.Object ref = gatewayProductKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gatewayProductKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *网关Mqtt productKey
       * </pre>
       *
       * <code>string gateway_productKey = 12;</code>
       */
      public com.google.protobuf.ByteString
          getGatewayProductKeyBytes() {
        java.lang.Object ref = gatewayProductKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gatewayProductKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *网关Mqtt productKey
       * </pre>
       *
       * <code>string gateway_productKey = 12;</code>
       */
      public Builder setGatewayProductKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gatewayProductKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *网关Mqtt productKey
       * </pre>
       *
       * <code>string gateway_productKey = 12;</code>
       */
      public Builder clearGatewayProductKey() {
        
        gatewayProductKey_ = getDefaultInstance().getGatewayProductKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *网关Mqtt productKey
       * </pre>
       *
       * <code>string gateway_productKey = 12;</code>
       */
      public Builder setGatewayProductKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gatewayProductKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gatewayDeviceName_ = "";
      /**
       * <pre>
       *网关Mqtt deviceName
       * </pre>
       *
       * <code>string gateway_deviceName = 13;</code>
       */
      public java.lang.String getGatewayDeviceName() {
        java.lang.Object ref = gatewayDeviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gatewayDeviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *网关Mqtt deviceName
       * </pre>
       *
       * <code>string gateway_deviceName = 13;</code>
       */
      public com.google.protobuf.ByteString
          getGatewayDeviceNameBytes() {
        java.lang.Object ref = gatewayDeviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gatewayDeviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *网关Mqtt deviceName
       * </pre>
       *
       * <code>string gateway_deviceName = 13;</code>
       */
      public Builder setGatewayDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gatewayDeviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *网关Mqtt deviceName
       * </pre>
       *
       * <code>string gateway_deviceName = 13;</code>
       */
      public Builder clearGatewayDeviceName() {
        
        gatewayDeviceName_ = getDefaultInstance().getGatewayDeviceName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *网关Mqtt deviceName
       * </pre>
       *
       * <code>string gateway_deviceName = 13;</code>
       */
      public Builder setGatewayDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gatewayDeviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gatewayDeviceSecret_ = "";
      /**
       * <pre>
       *网关Mqtt deviceSecret
       * </pre>
       *
       * <code>string gateway_deviceSecret = 14;</code>
       */
      public java.lang.String getGatewayDeviceSecret() {
        java.lang.Object ref = gatewayDeviceSecret_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gatewayDeviceSecret_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *网关Mqtt deviceSecret
       * </pre>
       *
       * <code>string gateway_deviceSecret = 14;</code>
       */
      public com.google.protobuf.ByteString
          getGatewayDeviceSecretBytes() {
        java.lang.Object ref = gatewayDeviceSecret_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gatewayDeviceSecret_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *网关Mqtt deviceSecret
       * </pre>
       *
       * <code>string gateway_deviceSecret = 14;</code>
       */
      public Builder setGatewayDeviceSecret(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gatewayDeviceSecret_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *网关Mqtt deviceSecret
       * </pre>
       *
       * <code>string gateway_deviceSecret = 14;</code>
       */
      public Builder clearGatewayDeviceSecret() {
        
        gatewayDeviceSecret_ = getDefaultInstance().getGatewayDeviceSecret();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *网关Mqtt deviceSecret
       * </pre>
       *
       * <code>string gateway_deviceSecret = 14;</code>
       */
      public Builder setGatewayDeviceSecretBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gatewayDeviceSecret_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object at_ = "";
      /**
       * <pre>
       *用户用TOKEN
       * </pre>
       *
       * <code>string at = 15;</code>
       */
      public java.lang.String getAt() {
        java.lang.Object ref = at_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          at_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户用TOKEN
       * </pre>
       *
       * <code>string at = 15;</code>
       */
      public com.google.protobuf.ByteString
          getAtBytes() {
        java.lang.Object ref = at_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          at_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户用TOKEN
       * </pre>
       *
       * <code>string at = 15;</code>
       */
      public Builder setAt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        at_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户用TOKEN
       * </pre>
       *
       * <code>string at = 15;</code>
       */
      public Builder clearAt() {
        
        at_ = getDefaultInstance().getAt();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户用TOKEN
       * </pre>
       *
       * <code>string at = 15;</code>
       */
      public Builder setAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        at_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serviceDeviceName_ = "";
      /**
       * <pre>
       *服务器Mqtt deviceSecret
       * </pre>
       *
       * <code>string service_deviceName = 16;</code>
       */
      public java.lang.String getServiceDeviceName() {
        java.lang.Object ref = serviceDeviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceDeviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *服务器Mqtt deviceSecret
       * </pre>
       *
       * <code>string service_deviceName = 16;</code>
       */
      public com.google.protobuf.ByteString
          getServiceDeviceNameBytes() {
        java.lang.Object ref = serviceDeviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceDeviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *服务器Mqtt deviceSecret
       * </pre>
       *
       * <code>string service_deviceName = 16;</code>
       */
      public Builder setServiceDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serviceDeviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器Mqtt deviceSecret
       * </pre>
       *
       * <code>string service_deviceName = 16;</code>
       */
      public Builder clearServiceDeviceName() {
        
        serviceDeviceName_ = getDefaultInstance().getServiceDeviceName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器Mqtt deviceSecret
       * </pre>
       *
       * <code>string service_deviceName = 16;</code>
       */
      public Builder setServiceDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serviceDeviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object usertype_ = "";
      /**
       * <pre>
       *用户类型直接返回用户类型，列：master, member,engineer
       * </pre>
       *
       * <code>string usertype = 17;</code>
       */
      public java.lang.String getUsertype() {
        java.lang.Object ref = usertype_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          usertype_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户类型直接返回用户类型，列：master, member,engineer
       * </pre>
       *
       * <code>string usertype = 17;</code>
       */
      public com.google.protobuf.ByteString
          getUsertypeBytes() {
        java.lang.Object ref = usertype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usertype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户类型直接返回用户类型，列：master, member,engineer
       * </pre>
       *
       * <code>string usertype = 17;</code>
       */
      public Builder setUsertype(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        usertype_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户类型直接返回用户类型，列：master, member,engineer
       * </pre>
       *
       * <code>string usertype = 17;</code>
       */
      public Builder clearUsertype() {
        
        usertype_ = getDefaultInstance().getUsertype();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户类型直接返回用户类型，列：master, member,engineer
       * </pre>
       *
       * <code>string usertype = 17;</code>
       */
      public Builder setUsertypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        usertype_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList appIots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAppIotsIsMutable() {
        if (!((bitField0_ & 0x00020000) == 0x00020000)) {
          appIots_ = new com.google.protobuf.LazyStringArrayList(appIots_);
          bitField0_ |= 0x00020000;
         }
      }
      /**
       * <pre>
       *home下面所有用户的iot信息
       * </pre>
       *
       * <code>repeated string app_iots = 18;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAppIotsList() {
        return appIots_.getUnmodifiableView();
      }
      /**
       * <pre>
       *home下面所有用户的iot信息
       * </pre>
       *
       * <code>repeated string app_iots = 18;</code>
       */
      public int getAppIotsCount() {
        return appIots_.size();
      }
      /**
       * <pre>
       *home下面所有用户的iot信息
       * </pre>
       *
       * <code>repeated string app_iots = 18;</code>
       */
      public java.lang.String getAppIots(int index) {
        return appIots_.get(index);
      }
      /**
       * <pre>
       *home下面所有用户的iot信息
       * </pre>
       *
       * <code>repeated string app_iots = 18;</code>
       */
      public com.google.protobuf.ByteString
          getAppIotsBytes(int index) {
        return appIots_.getByteString(index);
      }
      /**
       * <pre>
       *home下面所有用户的iot信息
       * </pre>
       *
       * <code>repeated string app_iots = 18;</code>
       */
      public Builder setAppIots(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAppIotsIsMutable();
        appIots_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *home下面所有用户的iot信息
       * </pre>
       *
       * <code>repeated string app_iots = 18;</code>
       */
      public Builder addAppIots(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAppIotsIsMutable();
        appIots_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *home下面所有用户的iot信息
       * </pre>
       *
       * <code>repeated string app_iots = 18;</code>
       */
      public Builder addAllAppIots(
          java.lang.Iterable<java.lang.String> values) {
        ensureAppIotsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, appIots_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *home下面所有用户的iot信息
       * </pre>
       *
       * <code>repeated string app_iots = 18;</code>
       */
      public Builder clearAppIots() {
        appIots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00020000);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *home下面所有用户的iot信息
       * </pre>
       *
       * <code>repeated string app_iots = 18;</code>
       */
      public Builder addAppIotsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAppIotsIsMutable();
        appIots_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:google.iproto.LoginRes)
    }

    // @@protoc_insertion_point(class_scope:google.iproto.LoginRes)
    private static final google.iproto.login.LoginResProto.LoginRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new google.iproto.login.LoginResProto.LoginRes();
    }

    public static google.iproto.login.LoginResProto.LoginRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginRes>
        PARSER = new com.google.protobuf.AbstractParser<LoginRes>() {
      public LoginRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRes> getParserForType() {
      return PARSER;
    }

    public google.iproto.login.LoginResProto.LoginRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_iproto_LoginRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_iproto_LoginRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"google/iproto/login/LoginRes.proto\022\rgo" +
      "ogle.iproto\"\367\002\n\010LoginRes\022\014\n\004uuid\030\001 \001(\t\022\r" +
      "\n\005token\030\002 \001(\t\022\020\n\010nickname\030\003 \001(\t\022\016\n\006gende" +
      "r\030\004 \001(\t\022\017\n\007address\030\005 \001(\t\022\017\n\007headurl\030\006 \001(" +
      "\t\022\013\n\003tel\030\007 \001(\t\022\016\n\006homeid\030\010 \001(\005\022\027\n\017user_p" +
      "roductKey\030\t \001(\t\022\027\n\017user_deviceName\030\n \001(\t" +
      "\022\031\n\021user_deviceSecret\030\013 \001(\t\022\032\n\022gateway_p" +
      "roductKey\030\014 \001(\t\022\032\n\022gateway_deviceName\030\r " +
      "\001(\t\022\034\n\024gateway_deviceSecret\030\016 \001(\t\022\n\n\002at\030" +
      "\017 \001(\t\022\032\n\022service_deviceName\030\020 \001(\t\022\020\n\010use" +
      "rtype\030\021 \001(\t\022\020\n\010app_iots\030\022 \003(\tB$\n\023google." +
      "iproto.loginB\rLoginResProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_google_iproto_LoginRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_iproto_LoginRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_iproto_LoginRes_descriptor,
        new java.lang.String[] { "Uuid", "Token", "Nickname", "Gender", "Address", "Headurl", "Tel", "Homeid", "UserProductKey", "UserDeviceName", "UserDeviceSecret", "GatewayProductKey", "GatewayDeviceName", "GatewayDeviceSecret", "At", "ServiceDeviceName", "Usertype", "AppIots", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
